### ISSUE TITLE
[Search] ui search dropdown - combo box versus select behavior

### ISSUE THREAD

**Issue by dustbort** [Semantic-Org/Semantic-UI#1368] opened 2014-12-03 17:49 UTC
Currently both `.ui.search` and `.ui.search.dropdown` have the same behavior when the user enters some text without making a selection, then changes focus (blurs the input): the user-entered text remains, even if it does not match a search result.  This can be seen on the [dropdown](http://semantic-ui.com/modules/dropdown.html) page where instead of selecting a U.S. state, a user can enter "foo" in the dropdown and the "foo" entry remains after blur.  While this behavior is consistent with a text box input, which allows any value, it is contrary to the select input, which restricts to selection from only the provided options.  My reasoning is based on the fact that `.ui.search.dropdown` is supported on `select` elements, and that `select` behavior with search enhancement is desirable.

The benefit (reason for existence) of the `select` input is that it limits the user to selecting a valid value on the form, without relying on format hints or post-entry validation. The `search` enhancement (string searching and displaying search matches) should not cause this fundamental behavior to be lost.  Also, doing so changes the select input into a combo box.  Select and combo box are very different: select would use the search enhancement as convenience to reduce typing and aid user memory, while still preserving the restriction to select an option; combo box would use the search enhancement for convenience in selecting an existing option but also as suggestions (e.g. to reduce duplication or variations) in allowing new entries.

At least if there were a way to choose whether the `.ui.search.dropdown` should have combo box behavior or select behavior, this would resolve the issue. Thanks.

**Comment by geemang2000** [comment] 2015-01-26 22:49
My question adds to this. What if we want the control be either choose something in the select or use the text e.g. foo for the form.   Is that possible. e.g. combo-box??

**Comment by itkach** [comment] 2015-01-27 22:27
> However, it is confusing to leave a different value showing in the search dropdown than will be submitted in the form. It would seem a better user experience to change the text back to the last selection (or none) if it loses focus and the user has not made a selection.

@dustbort Completely agreed. I made an attempt to implement this (set display text on the search input to text of actual selection on blur) but couldn't figure out how to get hold of the search input field, and in any case this feels like a brittle approach (making assumptions about details of `.ui.search.dropdown` implementation).  
@jlukic Various dropdown flavors in Semantic UI are very nice, but none of them provide equivalent to `select` with ability to select by typing.  This is very much needed.

**Comment by geemang2000** [comment] 2015-01-29 01:01
I created a combobox demo. Its pretty darn close.  All semantic-ui. 

I REALLY need the search to work. Any ideas??
http://plnkr.co/edit/d5IUrqfHyjLy0qcH4qYQ?p=preview

**Comment by jlukic** [comment] 2015-01-29 20:48
@geemang2000 
http://plnkr.co/edit/uuNRjf2aXmifhc95wU5A?p=preview

**Comment by jlukic** [comment] 2015-01-29 20:49
@itkach This should be the equivalent of select with search.
```html
<select class="ui search dropdown">
  <option value="">State</option>
  <option value="AL">Alabama</option>
  <option value="AL">Alabama</option>
  <option value="AK">Alaska</option>
  <option value="AZ">Arizona</option>
  <option value="AR">Arkansas</option>
  <option value="CA">California</option>
  <option value="CO">Colorado</option>
  <option value="CT">Connecticut</option>
  <option value="DE">Delaware</option>
</select>
```

**Comment by itkach** [comment] 2015-01-29 22:29
> This should be the equivalent of select with search.

@jlukic But it's not. It allows to leave the input field with arbitrary text in it.

**Comment by geemang2000** [comment] 2015-01-30 00:04
Exactly. Where I come from a combobox should act like a select, BUT... allow text input as well.

**Comment by jlukic** [comment] 2015-01-30 03:04
Just so im understanding, you are expecting it to clear any value not selected from the list on `blur`. This means they can continue to type anything in, but the expected result is that it must always show a value from the select?

**Comment by geemang2000** [comment] 2015-01-30 03:58
No on both. I want a real text input control (makes angular integration easy) that retains what the user types. And optionally lets them pick from the select list if it looks like a match. On blur it always retains the text in the input. Then closes the select if ithe didn't pick from it.

**Comment by geemang2000** [comment] 2015-01-30 04:00
My plnkr is pretty much a combo box. Just missing the searching select function.

**Comment by jlukic** [comment] 2015-01-30 04:11
The current search dropdown is a text input.. that "retains what the user types" and " lets them pick from the select list if it looks like a match" and on blur "retains the text in the input". I'm completely at a loss at what the issues is.

**Comment by itkach** [comment] 2015-01-30 04:29
I think @dustbort described the issue very well. There are two different use cases, two desired behaviors, basically two different widgets.  
1. User must be forced to pick a value from list, no other value is allowed (empty value is also a value, it can be in the list). Typing letters should select matching items. This is native `select` as implemented in Chrome or Firefox (although user experience is not awesome - in both these browsers there is no good visual feedback to help correlate what was typed with what was selected).
2. Editable text input field with dropdown of suggestions. We would user to pick item from the list we already have, but if they want to give us something that's not in the list that's fine too, we'll take it. This is 

The problem is that  `.ui.search.dropdown` acts like 1 but looks like 2.

`.ui.dropdown` provides a way to force a single item selection, but no selection by typing, so it's problematic to use for long lists such as list of US states or list of countries.

Restoring displayed text of `.ui.search.dropdown` to match selected item on blur would be a workaround to get less confusing user experience for use case 1, but it would break use case 2. Perhaps what we are really asking is a styleable equivalent of native `select` (possibly with nicer looking select-by-typing) and `.ui.search.dropdown` is just not the widget we are looking for.

**Comment by geemang2000** [comment] 2015-01-30 04:41
Plus I believe retrieving the user text is problematic with ui.search.dropdown. Also the dropdown caret doesn't work once something is typed. Lastly I had issues with validation with this text.

**Comment by jlukic** [comment] 2015-01-30 05:02
@geemang2000 I don't enjoy your tone or sense of entitlement. This is an open source project. I am one person managing 50 components, a build system and nearly 30 translations for free. If you have a bug, please submit a bug report. If you just want to complain about how you are unsatisfied, please do it somewhere else.

@itkach I can understand the desire to have the input show the actual selected value on `blur`. As stated before:

> Whatever text is left inside the input is not what is passed along with the form. The dropdown retains the original <select element, hides it, and then updates that native <select> element when a selection is made.

Perhaps `search select` dropdown should have a setting to adjust the text to the current selected value on blur. `forceSelection: true` or something like that.

**Comment by geemang2000** [comment] 2015-01-30 13:00
@jlukic 
Apologizes on my tone, honestly not my intent. I really like this project. I'm in the middle of converting one of our commercial products to Semantic. My goal is to give you all the details so you can make an informed direction choice. I've been battling a combo-box for a couple days. I think it'll be a great addition and from what I can see almost all the functionality is already present.  I'll gladly help where I'm able. 
I'll create issues for the possible defects I've noticed trying to make this work and create corresponding plnkr examples. 

One thing to consider. I'm using Angular which I'm sure many others will. If we could use a text input instead of a hidden input see (http://semantic-ui.com/modules/dropdown.html#/usage) it'd make angular validation and two-way binding really easy. We need to add ng-model="" and other directives. Unfortunately angular directives don't work on hidden inputs (without a lot of hacking).

**Comment by jlukic** [comment] 2015-01-30 17:15
I understand your frustration, obviously anyone who has been banging his head on the wall over a bug for several days would be a bit annoyed. I think the issue is i'm really having trouble nailing down your problems with an actionable issue. 

For example

Bug Report:
I expect (x) to do (y) when I use code (z), but instead it does (a). 

Feature Request
Currently (x) does (y). This doesn't make sense. It should instead do (z)

With itkach's remarks (correct me I'm wrong), I believe it could be boiled down to.

I feel *dropdown* should set the *search input* to the *currently selected dropdown menu choice*, when *the user finishes interacting with the dropdown* 

Which is a clear proposal which I can implement in code.

With your remarks, I think what you're getting at is:
I feel *dropdown* should allow *all input types for holding form data* so *angular bindings can be attached successfully for validation*.

Am I correct or is there something else?

**Comment by geemang2000** [comment] 2015-01-30 18:30
Thanks @jlukic I'll do a better job communicating these.

I believe you've nailed it!

**Comment by geemang2000** [comment] 2015-01-30 18:33
#2 could be something like ui.search.combo.dropdown

**Comment by geemang2000** [comment] 2015-02-01 14:04
@jlukic Should I open separate issues / feature requests?

**Comment by jlukic** [comment] 2015-03-26 17:13
This was resolved with `forceSelection`

**Closed by jlukic** 2015-03-26 17:13 UTC
Labels: Discussion

**Comment by cuixiping** [comment] 2015-05-28 14:04
combox is different with search dropdown.

   combox items will never be hidden. combox just scroll to the matched items.
   whatever content the user input, the combox dropdown menu always can be drop down.
   search dropdown items which does not match the user input will be hidden.

**Comment by jlukic** [comment] 2015-05-28 15:49
Im sorry I dont understand clearly what you are saying @cuixiping

**Comment by roybein** [comment] 2016-04-16 07:22
Just a hint, if you want to make your dropdown selection accept a value not in options menu, use setting [allowAdditions](http://semantic-ui.com/modules/dropdown.html#/settings) is a good choice.

**Comment by cuixiping** [comment] 2016-04-18 14:55
@jlukic   
Fox example, there is a dropdown with 4 items:  "a","b","c","d".   
For `combox dropdown`, if user type "c" in the input box,  item "c" is highlighted and "a","b","d" are also visible.  
For `search dropdown`, if user type "c" in the input box,  only item "c" is visible in the dropdown list and "a","b","d" should be hidden.  
Maybe I misunderstand them, but I hope there is a way to do the 2 different behaviors.

**Comment by mariusk** [comment] 2016-10-29 18:56
Just a few comments from another user needing a combobox allowing free inputs in addition to a searchable menu. The examples linked seem to work for 1.8 but not 2.2. I was able to make it work for 2.2 however, using a div with class `ui fluid search selection dropdown` with the usual hidden input element, initializing the dropdown with:

```javascript
    $('.ui.dropdown').dropdown({
      onChange: this.onChange,
      allowAdditions: true,
      forceSelection: true,
      hideAdditions: false
    });
```
and finally, on the next tick or later, calling $('.ui.dropdown').dropdown('set text', 'some default') to have it initialized properly. YMMV.
