### ISSUE TITLE
Dynamic added items can not be selected.

### ISSUE THREAD

**Issue by yandan66** [Semantic-Org/Semantic-UI#3371] opened 2015-11-20 13:22 UTC
I have add a item dynamicly but can not by set select the item immediately. But can be set selected after add other item. 
example:http://jsfiddle.net/yandan66/n82v59g9/1/
 I don not know why. Anyone can help me?

**Comment by IonutBajescu** [comment] 2016-07-12 17:36
Closing this since I'm unable to reproduce the issue.

@yandan66 feel free to reopen if you haven't fixed it in the meantime.

**Closed by IonutBajescu** 2016-07-12 17:36 UTC
