### ISSUE TITLE
Confused in Visibility.

### ISSUE THREAD

**Issue by orion110217** [Semantic-Org/Semantic-UI#5621] opened 2017-08-03 08:25 UTC
I tried to follow the instructions in the docs but still find it hard how to enable infinite scrolling inside tab menu. A static one also.

Here is the sample code I'm working on: https://jsfiddle.net/z79awx5r/

Also the code linked does the opposite of what I want. As the user scroll I want to load more cards.

**Comment by Banandrew** [comment] 2017-08-07 01:14
Hi @orion110217, `onBottomVisible()` is currently bugged and should be fixed with #5363, when it is, you should probably initialize the visibility component on `$('.ui.cards')` instead, because if you initialize it on every `.card`, the callback will be firing every time a `.card` appears on screen, and you probably don’t want it to happen.

You could either fork the component with the changes from that PR—don’t forget to exclude the visibility
 component in `semantic.json`’s `components` array and rebuild the framework—or think about some workaround using a different callback, for example, you could have an element after the `.ui.cards` container and use `onTopVisible()`.

As for doing the opposite of what you want, please give [this a read](https://stackoverflow.com/a/19491527/3685836). Closing as a duplicate of #5289.

**Closed by Banandrew** 2017-08-07 01:14 UTC
Labels: Duplicate

**Comment by orion110217** [comment] 2017-08-07 06:48
Thank you @Banandrew, I've followed everything you've told me and made it "worked", but I'm hitting an error which states that my elements are hidden and that I need to call refresh after it becomes visible. I don't get that error, also, how would I declare each card as hidden and only appear when onBottomVisible because what I currently have is I am just transitioning '.ui.cards' and although it works it is not my intended  outcome.

**Comment by Banandrew** [comment] 2017-08-10 06:59
@orion110217 Sorry for the delay, I’ll need to see the error to be specific, could you please reproduce it in a JSFiddle? You can add `.transition.hidden` classes to each `.ui.card` to hide them initially.
