### ISSUE TITLE
[Dropdown] - Search dropdown enter and blur couses first option selection

### ISSUE THREAD

**Issue by michtill** [Semantic-Org/Semantic-UI#4506] opened 2016-08-30 18:49 UTC
**Steps to Reproduce**
Enter and blur search selection dropdown with yet selected item.
1. Select some "not first" item in the search dropdown.
2. Again click into dropdown (in the search input, not only the arrow).
3. Click anywhere else outside the dropdown (blur the dropdown).

**Expected**
The dropdown should keep previesly selected item.

**Result**
The dropdown selects the first item in the list.

**Testcase**
http://jsfiddle.net/ba7dkjx4/

**WORKAROUND**
forceSelection: false //but on search dropdown it should be default false

**Comment by clthck** [comment] 2016-08-30 19:49
I can confirm this bug

**Comment by gizzard** [comment] 2016-08-31 10:37
The jsfiddle testcase is empty. I created one example here:
http://jsfiddle.net/0hfpccjz/

forceSelection: false is not an easy workaround for me because this allows to set a string which is not in the dropdown.

**Comment by brunotourinho** [comment] 2016-08-31 13:16
Confirmed!

**Comment by khornberg** [comment] 2016-09-01 01:59
I've gotten this as well

**Comment by khornberg** [comment] 2016-09-01 19:48
Setting `forceSelection` to `false` solved the problem for me.

**Comment by juice** [comment] 2016-09-19 12:37
This Issue should be included into the next Release.

**Comment by MaikeMota** [comment] 2016-10-07 12:39
We got the same issue in here.

**Comment by jlukic** [comment] 2016-10-07 14:46
Disable `selectOnKeydown` using `selectOnKeydown: false`, this is a separate behavior than whether it forces selection on blur.

**Comment by juice** [comment] 2016-10-07 15:20
In previous releases it was possible to type a few characters into the dropdown search and confirm the first selected item with tab. What do i have to do to make this work again?

**Comment by jlukic** [comment] 2016-10-19 00:06
@juice `forceSelection: false`

**Comment by juice** [comment] 2016-10-31 11:11
@jlukic Hi Jack, thanks for the tip, but this works only 50 percent of the time. I love this project, but right now the Dropdown part is a problem for many week. We use Dropdowns on a page with many Form Fields, most of them are generated from select fields and some of them are remote searches.

People want to type a few characters and tab to the next dropdown or text field. Right now, i have to choose between, dropdowns clear the current selection/add the first item to a multiselect or tab select is only working for some dropdowns if "forceSelection: false" is set, plus the typed characters are rendered over the selected text.

i feel like, as a default dropdowns should behave like native select fields. if you click on a dropdown, the current selection should not be cleared, the grey highlight should sit on the last selected item. i hope you can follow me. The Dropdowns worked as aspected pre 2.2.x and now it is a step by step process to see that with every release something gets fixed and something else stops working. I hope you can bring back the dropdown magic.

**Comment by jobes** [comment] 2016-11-02 20:38
function firstUnfiltered
partial workaround: showOnFocus: false but after key down is selected first again

**Comment by ajarti** [comment] 2017-04-13 08:47
@jlukic I did a little research and I see it's only for 'search multiple selection dropdown' and not for 'multiple selection dropdown', so it seems to be the combination of 'search' and 'multiple' where 'forceSelection: false' fails.

I hope that helps.

**Comment by Banandrew** [comment] 2017-04-13 12:54
Hi @ajarti, I can’t seem to reproduce, can you please fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln) to create a test case?

**Comment by lauri-elevant** [comment] 2017-05-03 10:03
@juice Thanks, the commit you linked looks good:
https://github.com/cbxp/Semantic-UI/commit/3fe5c551d35e7bb8463102a62feafe0b89c0e414

**Comment by jlukic** [comment] 2017-07-03 02:29
Can anyone provide a JSfiddle showing this issue in the current version? 

I'm testing in latest with `multiple search selection dropdown` and am not seeing it selecting incorrect value. Perhaps I'm not reproing correctly?

**Comment by jlukic** [comment] 2017-07-03 02:36
Oh hey.. this appears to be fixed in `next` release, but not current release. 

Apparently I noticed this on my own and fixed without linking back to this issue
https://github.com/Semantic-Org/Semantic-UI/commit/238ac3c8906330e0fcc1980fefeea0ae2dfb2bda

This will go out with `2.2.11` on tuesday.

**Closed** 2017-07-03 02:38 UTC
Labels: Discussion, Enhancement
