### ISSUE TITLE
[Menu] An item of the sub-menu in a parent-menu should be hide the `pointing` when it was clicked.

### ISSUE THREAD

**Issue by zenboss** [Semantic-Org/Semantic-UI#6552] opened 2018-08-29 03:39 UTC
### Steps
1. Put a sub-menu into the parent-menu
2. parent-menu with the CSS class-name `pointing`
3. click any item in the sub-menu
4. sub-menu will be retract back
5. BUT you can see the pointing `::after` will be still there of the item you clicked of the sub-menu

### Version
"semantic-ui-less": "^2.3.1",
---
![screenshot 2018-08-29 15 20 24](https://user-images.githubusercontent.com/928027/44763803-e92da580-aba0-11e8-9015-ddd7aa351765.png)
---
![screenshot 2018-08-29 15 20 36](https://user-images.githubusercontent.com/928027/44763804-e92da580-aba0-11e8-94ef-4019a6b9f8eb.png)
---
![screenshot 2018-08-29 15 20 45](https://user-images.githubusercontent.com/928027/44763806-e9c63c00-aba0-11e8-9aca-3b5d4c39b4f9.png)
---
![screenshot 2018-08-29 15 32 54](https://user-images.githubusercontent.com/928027/44763807-e9c63c00-aba0-11e8-9f9a-243439e95d2d.png)

### Testcase
[Fork, update, and replace to show the bug]:
https://jsfiddle.net/ca0rovs3/

**Comment by hammy2899** [comment] 2018-08-29 07:29
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6491

**Closed by hammy2899** 2018-08-29 07:29 UTC
Labels: Duplicate
