### ISSUE TITLE
[multiple search dropdown] 

### ISSUE THREAD

**Issue by JustSoMuch** [Semantic-Org/Semantic-UI#3610] opened 2016-01-26 02:08 UTC
Click event will be triggered repeatedly when I click the input.search.
It also occur in my project  and http://semantic-ui.com/modules/dropdown.html#/examples.
I need help. Thanks

**Comment by rijk** [comment] 2016-01-26 13:31
Duplicate of #3609

**Closed** 2016-02-02 03:46 UTC
