### ISSUE TITLE
gulp build is not building semantic.min.css

### ISSUE THREAD

**Issue by nestorvanz** [Semantic-Org/Semantic-UI#6067] opened 2018-01-03 00:40 UTC
In a fresh installation i am running "gulp build" but in the "dist" folder is not present semantic.min.css, theres only the semantic.min.js,  "components" and "themes" folder.

**Comment by wwp66650** [comment] 2018-01-03 10:46
I also have this issue

**Comment by himanshu230** [comment] 2018-01-03 11:59
I had the same issue
I solved it by changing the build-css gulp task. 
Following are the changes I made:
In file tasks/build/css.js in semantic folder, remove the following line
`compressedStream   = stream.pipe(clone());
 `

**Comment by nestorvanz** [comment] 2018-01-03 15:43
What are the changes that you made? @himanshu230

**Comment by himanshu230** [comment] 2018-01-03 16:11
@nestorvanz There is a file <path to your semantic folder>/tasks/build/css.js. Search for line 
`compressedStream = stream.pipe(clone());
`
Removing that line seems to solve the issue. 
It might be because later on, `compressedStream` is again set, which means that this clone stream is not piped to anything, creating backpressure.

**Comment by jjshammas** [comment] 2018-01-03 20:46
Hmm…that file hasn't changed since July 2016…

**Comment by Rex90** [comment] 2018-01-04 13:02
Been trying to figure out what I'm doing wrong all morning. Is this an issue with the semantic-ui release?

**Comment by hammy2899** [comment] 2018-01-04 13:21
@Rex90 This problem started after an update for [`gulp-clone`](https://www.npmjs.com/package/gulp-clone) was released.

I made a pull request this morning with a fix so hopefully it gets merged. You can do a temporary fix by commenting out a line as @himanshu230 mentioned in his [comment](https://github.com/Semantic-Org/Semantic-UI/issues/6067#issuecomment-354995802).

**Comment by fsworld009** [comment] 2018-01-04 17:44
I manually changed gulp-clone to 1.0.0 and remove that line as @himanshu230 suggested but still cannot get any css file after `gulp build` command. Any idea?

Both Semantic UI (2.2.13) and gulp CLI (3.9.1) are the latest.

**Comment by specimen151** [comment] 2018-01-09 13:39
I have found that it might have something to do with the file size. At least these are my findings:

Editing semantic.json, the "components" array, and removing e.g. half of the components will build the css with  no problem. Test with `gulp build-css`. You can remove whichever components you want (removing one is not enough), so that's why I think it has something to do with the total size of if.

**Comment by fsworld009** [comment] 2018-01-10 05:53
@specimen151 I think it might also because you forgot to specify the theme for certain components (or you put an invalid theme name?) in `theme.config` but you included those components in "components" array, which causes the build script fail. At least for me I am able to build all components into one css file.

**Comment by specimen151** [comment] 2018-01-10 09:44
@fsworld009 Could be, however I if I change the gulp-clone version to 1.0.0 or uncomment the clone line, like suggested above, it all works. And it also worked fine (clean install, no modifications) two weeks ago. I looked at the new gulp-clone, and there has been many changes there to the underlying dependencies. Maybe they don't work the same.

And also I am (w/o any mods) able to build all components, but not all at the same time. E.g. I specify the first half of the list of every component, builds fine. Then I replace with the second half of the list (of every component) and it builds fine. But when I have like 70% or more of the complete list of components, it seems like there is some buffer that's full or something, because it won't build, and it doesn't matter which components I remove... Anyway the above suggestions/pull-requests works for me.

**Comment by stepsplays** [comment] 2018-01-12 08:35
So, how is this coming along? Any fix without actually modifying the source files in npm? Can I somehow force the package to use gulp-clone 1.0.0??

**Comment by specimen151** [comment] 2018-01-12 09:05
Is @himanshu230 's fix of removing `compressedStream = stream.pipe(clone());` maybe better than staying with the old version of gulp-clone? The stream is set to a new stream just a few lines down anyway, so it seems unnecessary.

**Comment by stepsplays** [comment] 2018-01-12 09:24
I fixed this by generating a npm shrinkwrap with the git clone version 1.0.0 fixed the issue for me @specimen151 this might help you, change the version of gulp-clone  in semantic-ui package.json from ^1.0.0 to 1.0.0 in node_modules, generate a npm shrinkwrap (basically a package-lock with locked versions of packages and their dependencies), npm install inside semantic-ui folder in node_modules than you just do a clean npm install in the root folder of your projects package.json and it will generate a shrinkwrap with the correct version. From what i've read npm install first looks into shrinkwrap before installing and installs the versions specified inside shrinkwrap

**Comment by disrupticons** [comment] 2018-01-12 14:56
A cleaner fix IMO would be to simply install gulp-clone 1.0.0 as a dependency for your project, till a fix is released. This will replace the newer v1.1.1 that was installed by default.
```
npm i gulp-clone@1.0.0 --save-exact
```

**Comment by truesteps** [comment] 2018-01-12 15:05
@disrupticons true, i tried installing the depndency myself and reinstalled modules and it didn't work but seems like I just forgot to delete something and it didn't build really well, this is a much better solution

**Comment by jayphelps** [comment] 2018-01-15 18:55
This was fixed upstream in https://github.com/mariocasciaro/gulp-clone/issues/7. They reverted their change and released 1.1.2.

You may have to blow away your node_modules to pick up 1.1.2

```
rm -rf node_modules
npm install
```

**Comment by specimen151** [comment] 2018-01-16 09:32
So the issue could be closed then? Maybe @nestorvanz must do it?

**Comment by hammy2899** [comment] 2018-01-16 10:25
I can confirm the new [gulp-clone](https://github.com/mariocasciaro/gulp-clone) update did fix this. I am also going to close my [PR](https://github.com/Semantic-Org/Semantic-UI/pull/6070).

**Comment by jlukic** [comment] 2018-01-29 02:28
I've updated the project's package.json so it should fix any stale `node_modules`

**Closed** 2018-01-29 02:53 UTC

**Comment by jjshammas** [comment] 2018-02-21 22:17
In gulp-clone v2+, this seems to happen again!

**Comment by jayphelps** [comment] 2018-02-21 22:20
@jjshammas that's correct. The change they did was shifted from breaking 1.0 to 2.0. Semantic still uses v1 https://github.com/Semantic-Org/Semantic-UI/blob/5b681ca84e756d0d6080ecc6a3e2cdd40c0e3d50/package.json#L58

**Comment by chaseholdren** [comment] 2018-04-15 17:58
Would someone mind adding the version constraint to the `gulp-clone` peer dependency as well?

**Comment by CapitaineToinon** [comment] 2018-09-12 11:11
> I had the same issue
> I solved it by changing the build-css gulp task.
> In file tasks/build/css.js in semantic folder, remove the following line
> `compressedStream = stream.pipe(clone());`

Problem is still here, this solved the issue.

**Comment by j-cong** [comment] 2018-10-14 16:33
@jlukic Looks like this problem is back, as `"gulp-clone": "^2.0.1",` was updated. Shouldn't this issue be reopened?

**Comment by rsbepvb** [comment] 2018-10-16 22:01
Having the same problem.

**Comment by webberwang** [comment] 2018-10-17 04:18
Same issue happening

**Comment by Coteh** [comment] 2018-10-17 04:33
Was just having the same issue as well, and can confirm that the change applied in himanshu230's PR (#6631) fixes the problem.

**Comment by tuanhuu** [comment] 2018-10-17 04:58
> Was just having the same issue as well, and the change applied in himanshu230's PR (#6631) fixes the problem for me.

yep, me too,

**Comment by tuanhuu** [comment] 2018-10-17 05:55
How to import semantic.min.js i get error at line 11.
after that, i install jquery and import in index.js but nothing works
import * as $ from "jquery"
import "./semantic/dist/semantic.min.js"

**Comment by Sigvaard** [comment] 2018-10-20 11:29
this issue should be re-opened

**Comment by farrizal** [comment] 2018-10-20 16:34
yeah i got same problem, its doesnt build semantic.min.css

**Comment by jlukic** [comment] 2018-10-21 20:50
Fixed in `2.4.2` patch

**Comment by seunoyebode** [comment] 2019-01-18 07:33
I have the same problem "gulp build" doesn't build semantic.min.css and semantic.min.js

**Comment by hammy2899** [comment] 2019-01-18 07:53
@seunoyebode Please provide some more info like node, npm and SUI version.

**Comment by seunoyebode** [comment] 2019-01-18 07:59
@hammy2899 Node v8.11.4 npm 5.8.0 gulp CLI version 2.0.1 local version 3.9.1

**Comment by seunoyebode** [comment] 2019-01-18 09:17
Thanks @hammy2899 That worked. Although i had to install npx. It's working now.

By the way i think the getting started guide should be more explicit @jlukic 

Thanks you guys are doing a great job. I'm ditching Bootstrap!!!
