### ISSUE TITLE
form submit using api

### ISSUE THREAD

**Issue by Endhuine** [Semantic-Org/Semantic-UI#4443] opened 2016-08-17 16:00 UTC
I've defined a form
`<form class="ui form" id="form">

		<div class="fields">
			<div class="four wide field">
				<label>description<input
					name="description" type="text" placeholder="description">
			</div>
		</div>

		<div class="ui left floated green submit button" id="save-button">Save</div>
		<div class="ui reset button">Reset</div>

		<div class="ui error message"></div>
	</form>`

and it have validation which i'll avoid since it works fine

I've attached an api to my form like this:

```
$('#form')
			.form(formval)
			.api({
				url: 'fake.url',
				method: 'post',
				serializeForm: true,
				data: {
				},
				beforeSend: function(settings) {
					console.log("Data submitted: " + settings);
					return $('#form').form('is valid');
				},
				onSuccess: function(response) {
					// valid response and response.success = true
					location.reload();
				},
				onFailure: function(response) {
					// request failed, or valid response but response.success = false
					$('#form .error.message').text(response.message);
					$('#form').api('set error');
					console.log(response);
				}
			});
```

the problem is quite strange:
if i click on the save button everything works just fine.
if i press 'enter' to submit the form, seems like the api is gonna skip the onSuccess/onFailure part; but if i set a breakpoint inside beforeSend and then resume execution, again, everything works as expected. 
I'm searching a solution all the day long whit no result, maybe is a bug, maybe I'm (most probably) missing something?

Sorry, can't indent the js part.. today nothing is going right...

**Comment by Endhuine** [comment] 2016-08-18 07:30
I forgot this: submitting the form using enter seems firing the event 2 times, the first that got cancelled and the second that goes right.. here a screenshot

![image](https://cloud.githubusercontent.com/assets/10973609/17765437/2886dae4-6526-11e6-8d2a-571468b7ee1c.png)

**Comment by Endhuine** [comment] 2016-08-18 08:26
Ok, I've solved the problem adding: 
```
$("#form").keypress(function(event) {
		if (event.which == 13) {
			event.preventDefault();
		}
	});
```

**Comment by IonutBajescu** [comment] 2016-08-18 18:31
Closing since OP solved the problem himself.

**Closed by IonutBajescu** 2016-08-18 18:31 UTC

**Comment by MartinWickman** [comment] 2018-05-24 12:08
This bug still exists. Confirmed in version 2.3
