### ISSUE TITLE
[Form Validation] regression: get values with radio returns true or false

### ISSUE THREAD

**Issue by kapouer** [Semantic-Org/Semantic-UI#5713] opened 2017-08-28 10:01 UTC
I've setup two fiddles, one with semantic-ui 2.2.10 from cdn:
https://jsfiddle.net/xev09j67/2/
and one with semantic-ui 2.2.12 from semantic-ui-css package:
https://jsfiddle.net/mjL46gm4/1/

click on GET and SET buttons to show the problem.

**Comment by Banandrew** [comment] 2017-08-28 19:24
Hi @kapouer, it seems that it’s working correctly only when you specifically tell it that the fields are connected with `[]` postfix, e.g.: `name="fruit[]"`. Since `[]` postfix only makes sense in the PHP world, and is more of a back-end thing than anything, maybe it’d be better to automatically apply the same mechanism to multiple instances of `name="fruit"` pattern within a single form.

**Comment by gyuchang** [comment] 2017-11-17 05:58
This is a regression, introduced in 86ea20d5a09463cda6f2e98dacb824c23ee0b592

See [this comment](https://github.com/Semantic-Org/Semantic-UI/commit/86ea20d5a09463cda6f2e98dacb824c23ee0b592#commitcomment-25176800)

**Comment by kevinresol** [comment] 2017-11-22 15:11
This is pretty critical I would say.

**Comment by brandonparsons** [comment] 2017-12-14 20:06
Broke my app also.

**Comment by tincdev** [comment] 2017-12-18 11:19
a quick workaround

in semantic.js: line 1103



                 if(isRadio) {
                    if(values[name] === undefined || values[name] == false ) {
                     values[name] = (isChecked) ? value || true : false;
                  }

**Comment by kevinresol** [comment] 2017-12-18 11:41
> a quick workaround

This is still not correct. The value should not be a boolean, but a value of the radio element selected.

**Comment by tincdev** [comment] 2017-12-18 12:10
That what you will have! the value of the selected radio element, but in some case people use radio input without "value" attribute and if you do you will have a boolean value....

**Comment by kevinresol** [comment] 2017-12-18 15:14
ahhh yes you are right, I mis-read the `||`

**Comment by jlukic** [comment] 2017-12-22 06:08
I'll look at this over the hoildays.

**Comment by jlukic** [comment] 2018-01-29 03:01
I've merged in the fix from @tincdev it is the correct approach.

**Comment by jlukic** [comment] 2018-01-29 03:05
Will be fixed in `2.2.14` released later tonight.

**Closed by jlukic** 2018-01-29 03:05 UTC
Labels: Confirmed Bug
