### ISSUE TITLE
[Website] Scroll doesn't work properly on Google Chrome mobile

### ISSUE THREAD

**Issue by radiocity** [Semantic-Org/Semantic-UI#5195] opened 2017-03-24 07:48 UTC
There is some scroll hell on [theming](https://semantic-ui.com/examples/theming.html) page.
Browser: Google Chrome 56.0.2924.87
OS: Android 5.1 / Flyme
[Video](https://youtu.be/nPf2spEMPUc)

**Comment by Banandrew** [comment] 2017-03-24 08:51
Hi @radiocity and thanks, closing as a duplicate of #5012. I reposted your data there.

**Closed by Banandrew** 2017-03-24 08:51 UTC
Labels: Duplicate

**Comment by jlukic** [comment] 2017-04-04 14:48
I've fixed this with https://github.com/Semantic-Org/Semantic-UI/commit/52dbc6288e327d1b671b0d86019a23ef6d601bcc and will be deploying this fix early to the docs.
