### ISSUE TITLE
Basic Button not rendering correctly in IE11 (2.2.10)

### ISSUE THREAD

**Issue by michaelongithub** [Semantic-Org/Semantic-UI#5235] opened 2017-04-04 14:14 UTC
High

just semantic.min.css and semantic.min.js, no themes. Problem only in IE11.

The corners are ugly. Kind of thick. Can you look into that?

Can be seen in https://semantic-ui.com/elements/button.html#basic

Thank You
Michael

**Comment by Banandrew** [comment] 2017-04-04 14:59
Hi @michaelongithub, that’s just how it is with IE11, there’s nothing can be done on the framework’s end. The problem is with how SUI sets borders with `box-shadow`, and `box-shadow` produces fat corners in IE11 when used in conjunction with `border-radius`. If you really need it, you could override [basic buttons](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/button.less#L705) in `installation_folder/src/elements/button.overrides` to make them use regular borders.

Closing as a duplicate of #3126.

**Closed by Banandrew** 2017-04-04 14:59 UTC
Labels: Duplicate

**Comment by michaelongithub** [comment] 2017-04-04 15:03
Very kind of You to look into it and explaning, thanks a lot
