### ISSUE TITLE
Failure building CSS on 2.4.1

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#6728] opened 2019-01-10 10:07 UTC
Hi,

I've found a problem building CSS on 2.4.1. There's a small logical typo in `bower_components/semantic/tasks/build/css.js`

To fix the problem change the code around lines 99-100:
```
 compressedStream = stream
    .pipe(plumber())
```

into the following:
```
 compressedStream
    .pipe(plumber())
```

**Comment by seunoyebode** [comment] 2019-01-18 07:37
The line is already like that yet i still can't get semantic.min.css and semantic.min.js

**Comment by hammy2899** [comment] 2019-01-18 07:52
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6067

**Closed by hammy2899** 2019-01-18 07:52 UTC
Labels: Duplicate
