### ISSUE TITLE
WARN deprecated gulp-util@3.0.8: gulp-util is deprecated 

### ISSUE THREAD

**Issue by kaigouthro** [Semantic-Org/Semantic-UI#6660] opened 2018-11-08 08:43 UTC
is frozen here for 20 minutes

```
Kai@Frank MINGW64 /c/app/aina/var.www/html/aina (master)
$ npm install semantic-ui
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
Installing
------------------------------
Installing to semantic/
Copying UI definitions
Copying UI themes
Copying gulp tasks
Adding theme files
Creating gulpfile.js
Creating site theme folder C:\app\aina\var.www\html\aina\go\semantic\src\site\
[01:30:20] Starting 'create theme.config'...
Adjusting @siteFolder to:  site/
Creating src/theme.config (LESS config) C:\app\aina\var.www\html\aina\go\semantic\src\theme.config
```

**Comment by hammy2899** [comment] 2018-11-08 16:08
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6641

**Closed by hammy2899** 2018-11-08 16:08 UTC
Labels: Duplicate
