### ISSUE TITLE
Labels are broken again.

### ISSUE THREAD

**Issue by ShaneIsrael** [Semantic-Org/Semantic-UI#6576] opened 2018-09-12 21:47 UTC
Labels are broke in your release. Our stuff that uses your labels are suddenly being completely filled in. I noticed that on your own website the labels are also broken. 

This happened once before in the past but it looked like you guys fixed it relatively quick. It would seem that the issue is back again. 
https://semantic-ui.com/elements/label.html

![screen shot 2018-09-11 at 10 35 45 am](https://user-images.githubusercontent.com/1677199/45455085-29158200-b6a3-11e8-824c-0758ac9c257e.png)

**Comment by hammy2899** [comment] 2018-09-12 22:10
This issue was never fixed and is still an issue.

Duplicate of #6439

**Closed by hammy2899** 2018-09-12 22:10 UTC
Labels: Duplicate

**Comment by ShaneIsrael** [comment] 2018-09-12 22:55
@hammy2899 It seems its been an issue for months? Why wasn't it fixed in 2.3.3?

**Comment by jlukic** [comment] 2018-09-16 23:32
Fixed in `next`, caused by typo.
