### ISSUE TITLE
Icon Buttons shifted down when next to another div

### ISSUE THREAD

**Issue by adammhaile** [Semantic-Org/Semantic-UI#2874] opened 2015-08-19 01:40 UTC
In v2.0 any icon button gets shifted down by about 50% of its height when placed next to another element. Like this:

![image](https://cloud.githubusercontent.com/assets/957162/9346963/49c9b514-45f1-11e5-8f07-577122947295.png)

This happens when a single icon button or a group. See the html code below for the screenshot above. 
```html
<div>
    <div class="ui labeled action input">
        <div class="ui label">Width</div>
        <input type="text" style="" id="num_input" placeholder="">
        <button class="ui icon button" tabindex="-1" id="num_undo"><i class="undo icon"></i></button>
    </div>
    <div class="ui icon buttons">
        <button class="ui compact icon button" id="num_minus"><i class="minus icon"></i></button>
        <button class="ui compact icon button" id="num_plus"><i class="plus icon"></i></button>
    </div>
</div>
```

Through some trial and error I found that adding the following css, overriding the same block in semantic.min.css, to my site fixes the problem:

```css
.ui.icon.button>.icon, .ui.icon.buttons .button>.icon {
	vertical-align: inherit;
}
```
Since vertical align is "top" in the semantic css, I would think that's *supposed* to be the right thing, but clearly it's not doing what it should.

Any thoughts on why this is happening?

**Comment by jlukic** [comment] 2015-08-19 13:53
With just the part of the code you provided I am unable to replicate
http://jsfiddle.net/uhqas1st/

Setting to `middle` should make it look more exact as input is 2px taller due to its border. 
http://jsfiddle.net/fmd6fxy4/

**Comment by avalanche1** [comment] 2016-05-01 08:01
Closing until there's a test case.

**Closed by avalanche1** 2016-05-01 08:01 UTC
Labels: Cannot Reproduce, Discussion

**Comment by vladiks** [comment] 2018-01-26 11:44
I am struggling with the same problem. Attached index.html stripped to simplest html is doing the same problem. I can not reproduce it using jsfiddle using same html code and css (I really don't understand why and I am going crazy about it).

[index.zip](https://github.com/Semantic-Org/Semantic-UI/files/1667584/index.zip)

**Comment by avalanche1** [comment] 2018-02-26 06:59
without a testable testcase we cannot help unfortunately

**Comment by vladiks** [comment] 2018-02-26 10:55
Please, see index.html attached in previous post
