### ISSUE TITLE
Messages not showing up once inside ui grid

### ISSUE THREAD

**Issue by ewuletstalk** [Semantic-Org/Semantic-UI#2039] opened 2015-03-30 17:43 UTC
Messages aren't showing up inside ui grid. This is because ui grid applies font-size to 0 and ui.message is using font-size:1em. I'm assuming the font-size should be 1rem for ui.message?

**Comment by jlukic** [comment] 2015-03-30 20:49
There's a font size reset inside `ui grid`, nothing can show up as a direct descendent of grid except column or row.

This is due to whitespace caused by consecutive `inline-block`

Will be fixed in `2.0` when all grids use flexbox

**Closed by jlukic** 2015-03-30 20:49 UTC
