### ISSUE TITLE
Label - Basic Labels not styled properly

### ISSUE THREAD

**Issue by puresimmer** [Semantic-Org/Semantic-UI#6496] opened 2018-07-23 19:58 UTC
### Steps
If you set a label as basic it is not using the inverted (white) background.  It is using the label color.

You can see this on the label's documentation page at:
https://semantic-ui.com/elements/label.html

Check out the red pointing form label that says "Please enter a value" it just appears as solid red.

**Comment by ColinFrick** [comment] 2018-07-23 21:49
Duplicate of #6439

**Closed** 2018-07-23 22:08 UTC
Labels: Duplicate
