### ISSUE TITLE
Fluid dropdown cuts search bar on the right

### ISSUE THREAD

**Issue by murbard** [Semantic-Org/Semantic-UI#2445] opened 2015-06-23 02:06 UTC
https://jsfiddle.net/gb2zz94f/

Tried in Chromium and Firefox (latestish version) and the search bar inside the dropdown gets cut on the right side.

**Comment by jlukic** [comment] 2015-06-23 02:28
Seems to also occur in `2.0`, caused by `width: 100%` inherited from form. Input needs `width: auto;`
http://jsfiddle.net/5zo7vh75/

Example of fixed version with `width: auto;`
http://jsfiddle.net/so4modgL/

Will fix.

**Comment by murbard** [comment] 2015-06-23 02:44
It's hard to strip all of my code, but in my case, "width: auto"  yields too narrow a search input

**Comment by jlukic** [comment] 2015-06-23 21:38
It looks like 100% + margin is definitely wrong.

Can you provide a test case where
``css
.ui.dropdown .menu .input {
    width: auto;
}
```

Causes layout issues?

**Comment by jlukic** [comment] 2015-06-26 15:40
I'm going ahead and closing for now since there is a fix applied that fixes the presented test case.

**Closed by jlukic** 2015-06-26 15:40 UTC
Labels: Confirmed Bug
