### ISSUE TITLE
[Form] -  Searchable dropdown does not support accented characters convertion

### ISSUE THREAD

**Issue by almino** [Semantic-Org/Semantic-UI#4287] opened 2016-07-15 18:24 UTC
**Steps to Reproduce**
1. Click on a [searchable dropdown](http://semantic-ui.com/modules/dropdown.html#search-selection) with accented characters in its values (_e.g._ `Ceará`, `Piauí`, `Paraíba`, `Ciência`).
2. Type any word without accents (_e.g._ `ceara`, `piaui`, `paraiba`, `ciencia`).

**Expected**
Suggest the option `Ciência` when user types `cie`.

**Result**
The message is shown "No results found."

**Testcase**
http://jsfiddle.net/almino/159j8ujh/1/

**Comment by jlukic** [comment] 2016-07-29 06:40
Wow, exactly 1000 issues off, crazy chance. Duplicate of #3287

**Closed** 2016-07-29 06:41 UTC
Labels: Discussion, Duplicate

**Comment by lubber-de** [comment] 2019-01-24 18:51
Added option `ignoreDiacritics` to dropdown and search module for Fomantic-UI by [fomantic/Fomantic-UI#422](https://github.com/fomantic/Fomantic-UI/pull/422) 
See http://jsfiddle.net/t23uewyn/
