### ISSUE TITLE
[Request] Can you add this feature?

### ISSUE THREAD

**Issue by MajidCS** [Semantic-Org/Semantic-UI#3007] opened 2015-09-11 14:27 UTC
Can you add "Date Time Picker " ?

Like this is : ( Inline or dropdown or with dialog-boxes )

http://i.imgur.com/E44d8GI.png

I think you can make an integrated framework without using an external add-ons.

Thank you,

**Comment by unplugandplay** [comment] 2015-09-11 14:27
+1

**Comment by jlukic** [comment] 2015-09-11 14:50
Duplicate of #191

**Closed by jlukic** 2015-09-11 14:50 UTC
Labels: Duplicate
