### ISSUE TITLE
[Form][Dropdown] Requred select not focusable for browser error

### ISSUE THREAD

**Issue by jpass** [Semantic-Org/Semantic-UI#4943] opened 2017-01-26 09:26 UTC
When I use dropdown on select element that is requred browser can't display validation infromation on select, because its hidden.

My workaround for now is:
``` sass
.ui.dropdown>select
  border: 0 !important
  clip: rect(0 0 0 0) !important
  height: 1px !important
  margin: -1px !important
  overflow: hidden !important
  padding: 0 !important
  position: absolute !important
  width: 1px !important
  display: block!important
```

This way original select is not visible by user, but browser can show error information.

**Comment by Banandrew** [comment] 2017-02-05 23:33
@jpass could you please provide a test case? You can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by jpass** [comment] 2017-02-06 07:36
@Banandrew 
Simple select with "empty option" and required attribute.

http://jsfiddle.net/p97usuqf/13/

**Comment by Banandrew** [comment] 2017-02-06 07:58
@jpass Thank you. This appears to be a duplicate of #3694 that was labeled as “Fix/Change Declined”; please see it for more information. If it will help, adding a [novalidate](http://devdocs.io/html/attributes#novalidate-attribute) attribute to a form fixes it:
```HTML
<form action="/echo/html/" class="ui form" method="post" novalidate>
```
[Here’s a StackOverflow answer](http://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome/7264966#7264966) that explains it in detail:
>Chrome wants to focus on a control that is required but still empty so that it can pop up the message 'Please fill out this field'. However, if the control is hidden at the point that Chrome wants to pop up the message, that is at the time of form submission, Chrome can't focus on the control because it is hidden, therefore the form won't submit.
>
>So, to get around the problem, when a control is hidden by javascript, we also must remove the 'required' attribute from that control.

**Closed by Banandrew** 2017-02-06 07:58 UTC
