### ISSUE TITLE
Modal kills scrolling

### ISSUE THREAD

**Issue by SofeemLi** [Semantic-Org/Semantic-UI#6476] opened 2018-07-11 18:24 UTC
When I make a modal appear, it seems afterwards scrolling becomes impossible on my page, although arrow keys seem to work. It does the same thing on the Semantic UI site at the docs also. Is this because my borwser is being sucky?

**Comment by ColinFrick** [comment] 2018-07-12 05:08
Duplicate of #6449

**Closed** 2018-07-13 07:22 UTC
