### ISSUE TITLE
Adding a new component "Range"

### ISSUE THREAD

**Issue by lenok26** [Semantic-Org/Semantic-UI#2054] opened 2015-04-02 20:24 UTC
It would be cool to add the "**Range**". Sometimes it can be very useful. [Read more in the link] (http://codepen.io/anon/pen/azxawV?editors=110)

**Comment by ph7vc** [comment] 2015-04-02 20:59
#1703 

I agree; a very useful input element

**Comment by jlukic** [comment] 2015-04-02 22:23
Will most likely add a `ui slider` type something similar to one of these
http://codepen.io/collection/DgYaMj/

**Comment by jlukic** [comment] 2015-04-03 04:14
Duplicate of #1336  continue discussion there

**Closed by jlukic** 2015-04-03 04:14 UTC
Labels: Duplicate, UI Suggestion
