### ISSUE TITLE
Upgrade Font Awesome icons port to 4.7

### ISSUE THREAD

**Issue by ptylde** [Semantic-Org/Semantic-UI#4997] opened 2017-02-08 22:37 UTC
Semantic-UI currently includes a port of Font Awesome 4.5.6. There have been a lot of icons added since then that would be great to have included in the Semantic-UI icon set. What steps do we need to take to be able to upgrade the icons to 4.7?

**Comment by Banandrew** [comment] 2017-02-09 02:19
Hi @ptylde. Closing the issue as a duplicate of #4892; FA was already updated to 4.7 with #4766, and will soon be released along other changes with 2.2.8.

**Closed by Banandrew** 2017-02-09 02:19 UTC
Labels: Duplicate

**Comment by ptylde** [comment] 2017-02-09 13:28
@Banandrew Sorry for missing the other issue. I did look but obviously not hard enough! Thanks for letting me know!
