### ISSUE TITLE
[Form Validation] "is valid" buggy or designed this way?

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI#3407] opened 2015-11-30 19:58 UTC
When i run `$('.ui.form').form('is valid');` it adds error to field themselves, yet doesn't add any error messages. 

http://jsfiddle.net/896cxfyb/4/

Is this a bug or is it designed this way? Seems to me its a bug because without the error message being shown the user will never know how to change the input. The error message appears if you blur the element while keeping it in error, but its bad experience.

My thoughts on this are:
Either fields shouldn't show error and neither should error message be displayed (you're just checking not submitting)
Or
if the fields are showing error then error message should be shown as well.

Secondly i think a way to retrieve errors from the validator will come in handy to alot of developers with a slightly different use case.

My case is that i have a form broken down in multiple steps so before going over to the next step i validate that section of the form and only allow going to next step if the form is valid upto that point. 

P.S It works fine if i use `inline:true` because errors are applied to the field.

@jlukic

**Comment by ds0nt** [comment] 2015-12-17 15:25
Perhaps the prompts should not be added within the validation functions, but at a higher level, like after a submit event.

I've added a couple comments below in the form module code that I believe traces the issue

```javascript
is: {
          bracketedRule: function(rule) {
            return (rule.type && rule.type.match(settings.regExp.bracket));
          },
          valid: function() {
            var
              allValid = true
            ;
            module.verbose('Checking if form is valid');
            $.each(validation, function(fieldName, field) {

              // ---- validating each field
              if( !( module.validate.field(field, fieldName) ) ) {
                allValid = false;
              }
            });
            return allValid;
          }
        },

/// ...... which presumably ends up here

          // takes a validation object and returns whether field passes validation
          field: function(field, fieldName) {
            var
              identifier  = field.identifier || fieldName,
              $field      = module.get.field(identifier),
              fieldValid  = true,
              fieldErrors = []
            ;
            if(!field.identifier) {
              module.debug('Using field name as identifier', identifier);
              field.identifier = identifier;
            }
            if($field.prop('disabled')) {
              module.debug('Field is disabled. Skipping', identifier);
              fieldValid = true;
            }
            else if(field.optional && $.trim($field.val()) === ''){
              module.debug('Field is optional and empty. Skipping', identifier);
              fieldValid = true;
            }
            else if(field.rules !== undefined) {
              $.each(field.rules, function(index, rule) {
                if( module.has.field(identifier) && !( module.validate.rule(field, rule) ) ) {
                  module.debug('Field is invalid', identifier, rule.type);
                  fieldErrors.push(module.get.prompt(rule, field));
                  fieldValid = false;
                }
              });
            }
            if(fieldValid) {
              module.remove.prompt(identifier, fieldErrors);
              settings.onValid.call($field);
            }
            else {
              formErrors = formErrors.concat(fieldErrors);

              // ---- which runs this line if the field is invalid ---
              module.add.prompt(identifier, fieldErrors);
              settings.onInvalid.call($field, fieldErrors);
              return false;
            }
            return true;
          },
```


Or an easy hack would just be to add an optional boolean showErrors=true to the validation functions, which would then be set false from the "is valid" calls.

For the time being, I'll see if I can toggle my prompt templates between a blank div tag and the prompts default from the outside depending on if I want them to be visible, or invisible. 

Another hack I'm about to try is to call "remove prompt" for each element from my external code, as they are popping up.

Anyways, see my comments in this code.

**Comment by ds0nt** [comment] 2015-12-17 15:27
This is how I'm using it from angular. I'm adding a watch to the form("is valid") and then set my scope variables based on the result. But it unexpectedly adds error prompts all over my form.

```typescript
    var options = {
      fields: fields,
      inline: true,
      transition: 'fade',
      on: 'blur',
      keyboardShortcuts: false,
      templates: {
        prompt: error => {
          // if ($s.showErrors) {
            $(`<div class="ui pointing prompt label" style="position: absolute;z-index:1000;">${error}</div>`)
          // } else {
            // $(`<div class="ui pointing prompt label" style="display: none; position: absolute;z-index:1000;">${error}</div>`)
          // }
        }
      },
    }
    var form = $($e[0]).form(options);
    $s.$watch(() => $($e[0]).form("is valid"), v => $s.isValid = v)
```

**Comment by ds0nt** [comment] 2015-12-17 15:58
@talha-asad 

try changing the button to ``` type="submit" ```

**Comment by Banandrew** [comment] 2017-02-24 05:37
The issue is pretty old, but as of `2.2.8`, `is valid` no longer triggers UI updates, and only returns a boolean; UI updates can now be triggered with `validate form`. I’m closing it as fixed, but please let me know if I misunderstood something.

**Closed by Banandrew** 2017-02-24 05:37 UTC
Labels: Already Fixed
