### ISSUE TITLE
I'm closing the menu. The menus appear and disappear!

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#5820] opened 2017-09-29 21:00 UTC
Hello,
I use menu in header.
Words appear when you close the menu.
Not every menu.
It's on the menu on the far right.

My English is very poor.
I took a video for it.

Video;
http://sendvid.com/hp6bc8e7

```
<div class="ui menu">
	<a class="active item"><i class="user icon"></i> ego</a>
	<a class="active item"><i class="envelope icon"></i> mesaj (5)</a>
	<div class="ui dropdown item general_dropdown">
		<i class="plane icon"></i> kokpit
		<div class="menu">
			<a class="item"><i class="setting icon"></i>ayarlar</a>
			<a class="item"><i class="trash icon"></i>çöp kutusu</a>
			<a class="item"><i class="random icon"></i>takip ettiklerim</a>
			<a class="item"><i class="file text outline icon"></i>taslaklarım</a>
			<a class="item"><i class="pie chart icon"></i>istatistikler</a>
			<a class="item"><i class="idea icon"></i>gece moduna geç</a>
			<a class="item"><i class="ticket icon"></i>derdim var</a>
		</div>
	</div>
	<div class="ui dropdown item general_dropdown">
		<i class="world icon"></i> bildirim
		<div class="menu">
			<a class="item">atomu elleriyle bolen fizikci, <span class="c_orange">#34642085</span> entry'ni beğendi.</a>
			<a class="item">atomu elleriyle bolen fizikci, <span class="c_orange">#34642080</span> numaralı entry'ini favladı.</a>
			<a class="item">atomu elleriyle bolen fizikci, <span class="c_orange">#34642080</span> entry'ni beğendi.</a>
			<a class="item">atomu elleriyle bolen fizikci, <span class="c_orange">#34642085</span> numaralı entry'ini favladı.</a>
			<a class="item">atomu elleriyle bolen fizikci, <span class="c_orange">#34642085</span> entry'ni beğendi.</a>
			<a class="item">ivmurat, <span class="c_orange">#34642010</span> entry'ni beğendi.</a>
			<a class="item">desper, <span class="c_orange">#34566077</span> entry'ni beğendi.</a>
		</div>
	</div>
	<div class="ui dropdown item"></div>
</div>
```
I'm waiting for your help.
Thank you.

----

Additional info;
Since the menu is on the right, it automatically gets the "left" class name.
That's why he works erratically.
I expect a solution. :'(

**Comment by Banandrew** [comment] 2017-10-07 11:54
Hi @oguzhansari, sorry for the delay. I tried reproducing it in an isolated test case on JSFiddle, but couldn’t do it. Could you please fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/) to create a test case? Unfortunately, we can’t fix what we cannot reproduce.

**Comment by oguzhansari** [comment] 2017-10-07 20:51
I added a JSFiddle.
But he did not make an error there.
I have installed the subdomain.
JSFiddle;
https://jsfiddle.net/oguzhansari/ca0rovs3/90/
Subdomain;
http://test.oguzhansari.com

**Comment by Banandrew** [comment] 2017-10-08 05:07
@oguzhansari Could you please initialize that specific problematic dropdown on http://test.oguzhansari.com with `debug: true` and `verbose: true`?

**Comment by oguzhansari** [comment] 2017-10-08 11:27
I edited the Javascript code like this.

```
	$('.general_dropdown').dropdown({
		debug: true,
		verbose: true,
		onChange: function (value, text, $choice) {
			var datafunc = $(this).attr("data-call-function");
			if (datafunc != undefined) {
				var Params = [$(this), $choice, value, text];
				var AddonParameters = $(this).attr("data-function-add-parameter");
				if (AddonParameters != undefined) {
					var AddonParams = JSON.parse(AddonParameters);
					for (var i = 0; i < AddonParams.length; i++) {
						Params.push(AddonParams[i]);
					}
				}
				runFunction(datafunc, Params); //TEST için "TestJSFonksiyonAdı" adında fonksiyon mevcut.
			}
		}
	});
```

**Comment by Banandrew** [comment] 2017-10-09 11:44
@oguzhansari Thank you. This issue is a duplicate of #5741, and there’s already a PR that should fix it. Please see my comment there for a temporary solution.

**Closed by Banandrew** 2017-10-09 11:44 UTC
Labels: Duplicate
