### ISSUE TITLE
[Divider] - Divider misaligned to the left

### ISSUE THREAD

**Issue by greg-argulla** [Semantic-Org/Semantic-UI#4511] opened 2016-09-01 08:28 UTC
Found it on the Demo page on 9/1/2016
![image](https://cloud.githubusercontent.com/assets/7087833/18160524/7d702494-7060-11e6-948e-e8a677823f03.png)

Using Google Chrome: Version 52.0.2743.116 m

**Comment by IonutBajescu** [comment] 2016-09-04 10:22
Known issue I'm afraid.

Will most probably get fixed soon, but at the moment we're still hoping we find middle ground with W3C so we can keep the existing behaviour unchanged. 

Closing this as a duplicate of #4342.

**Closed by IonutBajescu** 2016-09-04 10:22 UTC
