### ISSUE TITLE
Avoid requesting google fonts

### ISSUE THREAD

**Issue by kaisbe** [Semantic-Org/Semantic-UI#6599] opened 2018-09-25 08:25 UTC
### Behavior description

Semantic UI needs to load these fonts locally, and not externally. This really results in **annoying behavior**, *slowing down UI loading* waiting for the fonts to be retrieved in case of slow internet connections.

### Expected Result
UI based on Semantic UI should load *seamlessly* and *quickly*.

### Actual Result
UI loads *slowly* and **gets interrupted** while waiting for google fonts to be retrieved from google's `fonts.gstatic.com` server.

### Version
2.4.0

**Comment by ColinFrick** [comment] 2018-09-25 08:40
Duplicate of #6422

**Closed** 2018-09-25 08:42 UTC
Labels: Duplicate
