### ISSUE TITLE
No longer have Jquery be a dependency

### ISSUE THREAD

**Issue by Jncocontrol** [Semantic-Org/Semantic-UI#6612] opened 2018-10-04 23:37 UTC
In general I think it's time to no longer have jQuery to be a dependency. 
Javascript has evolved into a much better than it was 6+ years ago and in some cases Jquery can really slow down the website performance and if performance is something that people are looking for, I think it would be best to longer have it.

**Comment by ColinFrick** [comment] 2018-10-05 04:35
Duplicate of #1175

**Closed** 2018-10-05 06:52 UTC
Labels: Duplicate
