### ISSUE TITLE
[Menu] input is not visible when width less than 767px

### ISSUE THREAD

**Issue by acczefly** [Semantic-Org/Semantic-UI#2992] opened 2015-09-10 06:40 UTC
on Medium devices is OK

![q -20150910143312](https://cloud.githubusercontent.com/assets/1452677/9781637/25981566-57c9-11e5-877f-6f0a0207017a.png)

on Small devices, input is not visible.

![q -20150910143609](https://cloud.githubusercontent.com/assets/1452677/9781711/df43c64a-57c9-11e5-9852-58b3b96a9b34.png)

**Comment by acczefly** [comment] 2015-09-10 06:43
Semantic-UI-2.0.3 works right, after upgrade to Semantic-UI-2.1.3, this bug happends.

**Comment by jlukic** [comment] 2015-09-10 06:45
Assuming this is duplicate of #2969

**Closed** 2016-05-01 08:03 UTC
Labels: Duplicate
