### ISSUE TITLE
[Segment] [Header] Top attached header has a negative margin-top

### ISSUE THREAD

**Issue by ocharles** [Semantic-Org/Semantic-UI#5462] opened 2017-06-13 15:27 UTC
See the following fiddle: https://jsfiddle.net/3rf9jtdu/

I argue that the top alignment of the first table cell's segment (top left segment) should be the same as the header's top alignment (top right). However, the header is the `:first-child` of a table, so it ends up having a negative margin, pulling it out of the padding of the table cell, and thus is out of alignment.

**Comment by ocharles** [comment] 2018-06-05 22:14
If this is to be closed it should only be because it duplicates #5436

**Comment by hammy2899** [comment] 2018-07-26 17:33
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/5436

**Closed by hammy2899** 2018-07-26 17:33 UTC
Labels: Duplicate

**Comment by lubber-de** [comment] 2019-01-05 17:52
Fixed in https://github.com/fomantic/Fomantic-UI 2.4.4
