### ISSUE TITLE
Modal ugly animation by scrollbar disappearing

### ISSUE THREAD

**Issue by andresespinosapc** [Semantic-Org/Semantic-UI#4207] opened 2016-07-03 07:31 UTC
If I am in a page that have a scrollbar and I open a small modal, the scrollbar does obviously disappear, but this causes an ugly animation, because I can notice the modal moving to the right when opened and to the left when closed.

Here's a fiddle showing the problem: http://jsfiddle.net/andresespinosapc/s3fbhdhc/
Please resize the result window to the maximum possible to notice the problem in the animation with more detail, the larger the screen the more noticeable the problem is. Then click the "Open modal" button  and you will see the modal moving to the right abruptly, close the modal and you will see the opposite.
I remark that the movement is not much, but noticeable as an ugly animation effect.

**Comment by philrykoff** [comment] 2017-03-02 14:29
Seems to be fixed with the current version, no ugly animation visible.

**Comment by Banandrew** [comment] 2017-03-02 14:37
I think it’s a duplicate of #2061.

**Closed by Banandrew** 2017-03-02 14:37 UTC
Labels: Duplicate

**Comment by lubber-de** [comment] 2019-02-08 16:33
We fixed this in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/468
See https://jsfiddle.net/smudoy1k/5/
