### ISSUE TITLE
I made an update Popup is broken (2.2.6 > 2.2.11)

### ISSUE THREAD

**Issue by oguzhansari** [Semantic-Org/Semantic-UI#5590] opened 2017-07-26 10:38 UTC
I upgraded the version.
Popup is broken.

In the first picture you can see the element.
![semanticui_popup1](https://user-images.githubusercontent.com/13555457/28616983-56d26ec4-7207-11e7-8558-f8cf4d1c7276.png)

In the second picture you can see the wrong one.
![semanticui_popup](https://user-images.githubusercontent.com/13555457/28616982-56cd5baa-7207-11e7-8656-0ded6b148a55.png)

I'm getting the value [data].
$('.general_hpopup').popup({
	hoverable: true,
});

**Comment by Banandrew** [comment] 2017-07-27 00:28
Hi @oguzhansari, thanks, I’m assuming it’s a duplicate of #5549.

**Closed by Banandrew** 2017-07-27 00:28 UTC
Labels: Duplicate

**Comment by jlukic** [comment] 2017-08-06 23:56
This will be fixed with #5549
