### ISSUE TITLE
"e.fn.form.settings is undefined" form validation

### ISSUE THREAD

**Issue by ashucg** [Semantic-Org/Semantic-UI#5335] opened 2017-05-04 21:44 UTC
I am using semantic-ui 2.2.10 and the minimal example found on the official website to validate number  type in a form, but on the blur event I am getting "e.fn.form.settings is undefined" error in the console. I have tried integer, decimal and number types but still getting the same error.

**Comment by Banandrew** [comment] 2017-05-05 01:12
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by ashucg** [comment] 2017-05-05 16:54
Hi, it is pretty strange that the code is working on a JSFiddle but on the website it is throwing up the above mentioned error. I have tried different ways on JSFiddle to reproduce the error but it is not happening so I guess it must some JS conflict on the website I am working on. What do you think?

**Comment by Banandrew** [comment] 2017-05-05 22:22
>but on the website it is throwing up the above mentioned error

Do you mean SUI website or the website you’re working on? It’s absolutely possible that there’s some kind of a conflict, in any case, we can’t fix what we cannot reproduce, so I’ll be closing the issue. If you’ll find that it’s an issue, please let me know and I’ll reopen it.

**Closed by Banandrew** 2017-05-05 22:22 UTC
Labels: Needs Test Case

**Comment by ashucg** [comment] 2017-05-06 15:45
Sure, I will let you know if I am able to reproduce it on fiddle. Thanks for your time!
