### ISSUE TITLE
[Tooltip] immediately disappears after being shown on Firefox v52

### ISSUE THREAD

**Issue by Frank1604** [Semantic-Org/Semantic-UI#5171] opened 2017-03-15 10:34 UTC
Since Firefox update to 52 (64bit) JS-Tooltips no longer work properly. Take a look at Semantic Ui Docs page to see the issue. -> https://semantic-ui.com/modules/popup.html#tooltip
The tooltips disappear immediately after they appear.

**Comment by Thomas12** [comment] 2017-03-15 16:03
Same problem here, just wanted to open an issue-ticket.
Firefox 52 (32 Bit): tooltip expands and hides immediately.
Firefox 47 (32 Bit) or IE 11: tooltip expands and stays visible.

**Comment by NoSoyTsundere** [comment] 2017-03-15 17:50
Confirmed on Ubuntu 16.10 (x86_64) with Firefox 52

**Comment by Giwayume** [comment] 2017-03-17 03:17
You probably already have this figured out, but explicitly specifying the "transform" property for the transition instead of saying "all" fixes the issue.

```
[data-tooltip]:before {
	opacity:0;
	-webkit-transform:rotate(45deg) scale(0)!important;
	transform:rotate(45deg) scale(0)!important;
	-webkit-transform-origin:center top;
	transform-origin:center top;
	-webkit-transition:transform .1s ease;
	transition:transform .1s ease
}
[data-tooltip]:after {
	opacity:1;
	-webkit-transform-origin:center bottom;
	transform-origin:center bottom;
	-webkit-transition:transform .1s ease;
	transition:transform .1s ease
}
```

**Comment by Thomas12** [comment] 2017-03-17 10:26
Giwayume, great, it works! Thank you!

**Comment by jlukic** [comment] 2017-03-28 16:34
Just tested in `52.0.2` for Windows 32bit and was unable to reproduce.

Perhaps this was fixed in one of the 2 patches so far? Can anyone confirm

**Comment by Banandrew** [comment] 2017-03-28 16:47
@jlukic Can confirm that `52.0.2` fixed the no-JS tooltips. There’s another issue now: when a tooltip is shown, in some cases it “expands” by 1px either vertically, or horizontally, [here’s an example](http://i.imgur.com/8e7MrUg.gifv)—that’s 32-bit Firefox on Windows 10. Shall we track it separately?

**Comment by daneren2005** [comment] 2017-03-29 21:48
I have `52.0.1` on a VM and it is broken.  I have `52.0.2` on my Windows host machine and it works there.  I think that this is indeed just a browser issue which FF already fixed in a patch.

**Comment by jlukic** [comment] 2017-04-10 02:39
I'm testing it out now. Hopefully I can repro

**Comment by jlukic** [comment] 2017-04-10 02:59
I think this is fixed by FF closing issue

**Closed by jlukic** 2017-04-10 02:59 UTC
Labels: Confirmed Bug, High Priority
