### ISSUE TITLE
[Popup] - onHide event fired twice

### ISSUE THREAD

**Issue by ErvinLlojku** [Semantic-Org/Semantic-UI#4752] opened 2016-11-16 16:47 UTC
While using popup component i noticed that _onHide_ event fired was **fired twice**!
Can you please check? 
Thank you!
```
$('.browse.item').popup({
      popup: '.browse.popup',
      on: 'click',
      onShow: () => {
        console.log('onShow');
      },
      onHide: () => {
        console.log('onHide');
      }
    });
```
![image](https://cloud.githubusercontent.com/assets/11721817/20356338/882f9e8c-ac24-11e6-816d-a74287f624b1.png)

**Comment by Banandrew** [comment] 2017-02-12 10:31
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment] 2017-02-12 10:32
@ErvinLlojku Sorry about that, there’s no need to provide a test case—closing the issue as a duplicate of #4722.

**Closed by Banandrew** 2017-02-12 10:32 UTC
Labels: Duplicate

**Comment by lubber-de** [comment] 2019-02-11 23:27
Fixed in Fomantic-UI by https://github.com/fomantic/Fomantic-UI/pull/481
See http://jsfiddle.net/bm1gzosv/1/
