### ISSUE TITLE
[Dropdown] Sub-menu positioning issue

### ISSUE THREAD

**Issue by adampoczatek** [Semantic-Org/Semantic-UI#6541] opened 2018-08-20 11:04 UTC
### Steps

Scroll down to your dropdown menu so that there's not enough space to open. The dropdown will open above the dropdown menu, which is correct, however, when you then try to open the sub nav the dropdown gets repositioned incorrectly.

### Expected Result

The dropdown should keep its original position.

### Actual Result

![2018-08-20_11-53-28](https://user-images.githubusercontent.com/1275098/44336923-e0d2bd80-a470-11e8-816a-0479c01d9d9c.gif)

### Version
2.3

### Testcase
You can replicate it on the [Semantic UI docs](https://semantic-ui.com/modules/dropdown.html)

**Comment by ColinFrick** [comment] 2018-08-20 11:11
Duplicate of #6007

**Closed** 2018-08-20 11:15 UTC
Labels: Duplicate
