### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Isigiel** [Semantic-Org/Semantic-UI#4531] opened 2016-09-06 10:08 UTC
I'm on latest npm and node, using the git bash on windows 10. I get this every time I try to npm-install semui
http://i.imgur.com/vq75ZNd.png
Hope that helps, I can provide additional info.

_edit_ Additional testing shows, it works fine with powershell
_edit 2_ Although the second question is not preselected to Yes (this is my project folder) and crashes the install if yes isn't actively selected

**Comment by ilanah** [comment] 2016-09-07 13:24
Also setting up for meteor is not working - giving some errors

**Comment by MarkoCen** [comment] 2016-09-09 20:58
@Isigiel 
I just successfully installed the latest npm on Windows 7, make sure you run the `cmd.exe` with administrator privileges

**Comment by Isigiel** [comment] 2016-09-10 06:35
@MarkoCen I was using Git bash. I think that should works as well ...

**Comment by IonutBajescu** [comment] 2017-03-12 00:33
Closing as a duplicate of #4292.

**Closed by IonutBajescu** 2017-03-12 00:33 UTC
