### ISSUE TITLE
divider err

### ISSUE THREAD

**Issue by DasonCheng** [Semantic-Org/Semantic-UI#4557] opened 2016-09-18 03:07 UTC
![image](https://cloud.githubusercontent.com/assets/16243342/18612564/0f17334c-7d90-11e6-8fbf-1b9d464dc400.png)

**Comment by DasonCheng** [comment] 2016-09-18 03:13
```
.ui.grid>.column+.divider, .ui.grid>.row>.column+.divider {
    /* left: auto; */
}
.ui.vertical.divider {
    position: absolute;
    z-index: 2;
    top: 50%;
    left: 50%;
    margin: 0;
    padding: 0;
    width: auto;
    height: 50%;
    line-height: 0;
    text-align: center;
    -webkit-transform: translateX(-50%);
    transform: translateX(-50%);
}
```

**Comment by IonutBajescu** [comment] 2016-09-18 10:25
Thanks for the screenshots, but I'm afraid this is a known issue.

I'm closing this as a duplicate of #4342.

**Closed by IonutBajescu** 2016-09-18 10:25 UTC
