### ISSUE TITLE
toast function

### ISSUE THREAD

**Issue by dbavuugarid** [Semantic-Org/Semantic-UI#6787] opened 2019-04-12 04:21 UTC
when will you enable toast function in semantic ui

**Comment by lubber-de** [comment] 2019-04-12 06:50
@dbavuugarid Fomantic-UI has a Toast module built in since 2.6.0
https://fomantic-ui.com/modules/toast.html

**Comment by dbavuugarid** [comment] 2019-04-12 08:07
thank you for your comment 

is there any difference between semantic and fomantic?
i have been using Semantic UI, is there any problem to switch from semantic UI to fomatic UI

**Comment by dbavuugarid** [comment] 2019-04-12 08:18
> @dbavuugarid Fomantic-UI has a Toast module built in since 2.6.0
> https://fomantic-ui.com/modules/toast.html

**Comment by lubber-de** [comment] 2019-04-12 09:27
> is there any difference between Semantic UI and Fomantic UI?
> i have been using Semantic UI, is there any problem to switch from Semantic UI to Fomatic UI

@dbavuugarid 
Your existing code should work just fine as it is in when using Fomantic-UI (and immediatly gains tons of bugfixes and new enhancements :D ) because it is still backward compatible to SUI
We have documented every new enhancement or changes in the docs (for example the rating-module).
Btw, you should reopen this issue here in SUI, as long as it is not fixed/implemented or denied by the repo-owner

**Comment by hammy2899** [comment] 2019-04-12 17:06
This is a duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/1430.

As @lubber-de has said, FUI already has a toast module implemented.

**Closed by hammy2899** 2019-04-12 17:06 UTC
Labels: Duplicate
