### ISSUE TITLE
Please use Webpack-friendly URLs

### ISSUE THREAD

**Issue by explorigin** [Semantic-Org/Semantic-UI#3724] opened 2016-02-20 06:36 UTC
For some context, see my longer comment [here](https://github.com/Semantic-Org/Semantic-UI/issues/3533#issuecomment-186520229).

When using `url()` or `@import` directives in generated CSS, please pre-pend relative paths with `./`.  This allows Webpack's [CSS-loader](https://github.com/webpack/css-loader).

Without this change, attempting to include semantic-ui in the normally accepted ways: 
`@import "semantic-ui/dist/semantic.css";`
or
`require("semantic-ui/dist/semantic.css");`

will result in an error that looks like: 

`Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'themes/default/assets/images/flags.png' in <project_folder>/node_modules/semantic-ui/dist`

**Comment by egbertp** [comment] 2016-02-21 17:27
+1

**Comment by Hellenic** [comment] 2016-02-27 10:10
+1

**Comment by ArnaudValensi** [comment] 2016-03-02 15:47
+1

**Comment by rickyPanzer** [comment] 2016-03-08 17:10
+1

**Comment by CameronK** [comment] 2016-03-13 08:31
+1

**Comment by mcrawshaw** [comment] 2016-03-17 11:03
+1

**Comment by emzero** [comment] 2016-03-27 01:18
+1

**Comment by jlukic** [comment] 2016-03-29 14:18
I think the only static asset is the flags, I'll fix the relative paths

**Comment by explorigin** [comment] 2016-03-29 14:27
> I think the only static asset is the flags, I'll fix the relative paths

And icon fonts:
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L7013

**Comment by jlukic** [comment] 2016-04-01 16:18
I've prefixed all relative paths with `./` appears to be fine with css. Hopefully this should fix webpack. @explorigin can you verify with `next` branch?

**Comment by explorigin** [comment] 2016-04-01 19:25
@jlukic Whenever I run `gulp build` the resulting `dist/semantic.css` paths are not changed. Perhaps they're sanitized by something in the build process?

**Comment by atomi** [comment] 2016-04-01 20:25
I just ran this update by using the latest commit:
 ```npm i --save semantic-ui/semantic-ui#94f9ced66e9713b998d853732eae27080f687e10``` with url-loader for `(png|woff|woff2|eot|ttf|svg)`  and it works fine.

**Comment by jlukic** [comment] 2016-04-01 21:23
Since my first commit I also had to modify the paths in the concatenated css. Our gulp pipeline uses `concatCSS` which decided to rewrite the urls as well..

It should be fixed with 	d9247de

**Comment by mcrawshaw** [comment] 2016-04-01 21:43
Try again @explorigin.  I can confirm it is working as expected.  Thanks.

**Comment by explorigin** [comment] 2016-04-01 22:29
Looks good.  Muchas Gracias.

**Closed** 2016-04-01 22:29 UTC
Labels: Evaluating Bug / Change

**Comment by jlukic** [comment] 2016-04-13 01:08
Looks like this is causing issues on windows #3903
