### ISSUE TITLE
[Dropdown] Change direction of Dropdown menu

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5179] opened 2017-03-17 08:35 UTC
I'm using Semantic-UI and Angular for developing a web app.
Following to [Semantic-UI documentation](https://semantic-ui.com/modules/dropdown.html) about dropdown, I created the following button:

    <div class="ui dropdown button">
      <div class="text">Menu</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item" (click)="onClickSuItem(m)" *ngFor="let m of menu"> <i class="icon {{m.icon}}"></i>{{m.name}}</a>
      </div>
    </div>

I would like to change the direction of the menu, and set it on the left, instead of right. Do you know how can I reach that?
Could be a good idea to have a `direction`/`orientation` option?

Here is a [Plunker](https://plnkr.co/edit/JOMPaWDBi3LpzkmSB9f7).

**Comment by vinayakkulkarni** [comment] 2017-03-17 09:25
Did you get a chance to read : [Menu Direction in Dropdown](https://semantic-ui.com/modules/dropdown.html#menu-direction) ?

**Comment by smartm0use** [comment] 2017-03-17 09:32
Yes, I read it, but it wasn't what I'm looking for. I mean direction of the dropdown menu, not direction for a sub-menu of the dropdown menu.

**Comment by vinayakkulkarni** [comment] 2017-03-17 09:34
Guess, what you're asking is similar to this issue: #3716

**Comment by vinayakkulkarni** [comment] 2017-03-17 09:36
But still, that's again dropdown, then (left)/(right) side menu..

**Comment by smartm0use** [comment] 2017-03-17 09:38
I see, thank you anyway. So that's a feature request that has not yet been accomplished. Am I right?

**Comment by Banandrew** [comment] 2017-03-17 10:26
Hi @smartm0use, try to use `<div class="ui left pointing dropdown button">`, it’s the only thing that can work out of the box. Closing the issue as a duplicate of #3716, I see no difference between the two.

**Closed by Banandrew** 2017-03-17 10:26 UTC
Labels: Duplicate

**Comment by smartm0use** [comment] 2017-03-17 10:55
@Banandrew As I said before that solution wasn't I looking for. It should be like [Floating](https://semantic-ui.com/modules/dropdown.html#floating) appearance, but I need one button instead of two.

![dropdown](https://cloud.githubusercontent.com/assets/5399265/24040202/8bd025d2-0b08-11e7-828e-abadc8c1c877.png)

**Comment by nebrelbug** [comment] 2018-01-25 04:32
Are there any updates on this issue? I'd love this feature too.

**Comment by Utsho-Sadhak-Joy** [comment] 2020-07-07 04:24
I am looking for bottom left direction dropdown
