### ISSUE TITLE
[Popup] - Variations bug

### ISSUE THREAD

**Issue by cstd-tudoudou** [Semantic-Org/Semantic-UI#5597] opened 2017-07-27 13:13 UTC
As you can see, when the position of the pop-up window is insufficient, it will leave the position where it should appear, or even disappear.
<img src="https://raw.githubusercontent.com/cstd-tudoudou/Fragmented-files/master/img/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-07-27%20%E4%B8%8B%E5%8D%888.58.26.png">
And this.
<img src="https://github.com/cstd-tudoudou/Fragmented-files/blob/master/img/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-07-27%20%E4%B8%8B%E5%8D%888.58.50.png?raw=true">
Finally, thank you for your work.

**Comment by Banandrew** [comment] 2017-07-28 04:30
Hi @cstd-tudoudou, I think it might be a duplicate of #5549. Somebody will reopen this issue if we find that it’s not.

**Closed by Banandrew** 2017-07-28 04:30 UTC
Labels: Duplicate

**Comment by jlukic** [comment] 2017-08-06 23:55
This will be fixed with #5549
