### ISSUE TITLE
All radios selected by default (R2.0 bug)

### ISSUE THREAD

**Issue by deneuxa** [Semantic-Org/Semantic-UI#2505] opened 2015-07-02 17:45 UTC
you can see this on the homepage ;)
I have the same problem with all my radios buttons

http://www.semantic-ui.com/

![capture d ecran 2015-07-02 a 19 44 35](https://cloud.githubusercontent.com/assets/359847/8483711/db526df6-20f2-11e5-9842-d473a63caae5.png)

**Comment by dwightbcoder** [comment] 2015-07-02 18:02
I've experienced the same issue when testing 2.0 with my application.

**Comment by jlukic** [comment] 2015-07-04 16:56
There appears to be a bug with radios when none are selected by default. It's a holiday hear in the US and I'm away from a code editor. But I'll patch this on monday.

**Comment by jlukic** [comment] 2015-07-04 17:04
Funny enough this is chrome only.

**Comment by jlukic** [comment] 2015-07-04 17:10
It looks like `:indeterminate` triggers in Chrome when no radios are selected. This causes radio checkbox to appear incorrectly.

Fixed in `2.0.1`

**Closed** 2015-07-04 17:12 UTC
Labels: Confirmed Bug, High Priority

**Comment by deneuxa** [comment] 2015-07-04 17:42
Thanks Jack !

**Comment by svanderbleek** [comment] 2015-07-07 13:31
Awesome, this was driving me crazy!

**Comment by jlukic** [comment] 2015-07-20 19:15
There was a regression in this issue in `2.0.4` will be patched again today.. apologies
