### ISSUE TITLE
npm install semantic-ui --save hangs on Windows 10

### ISSUE THREAD

**Issue by fearofcode** [Semantic-Org/Semantic-UI#6740] opened 2019-01-27 06:57 UTC
### Steps

`npm install semantic-ui --save`

Select automatic installation
Select default installation folder (`semantic/`)

### Expected Result

Installation should complete as described as shown in https://semantic-ui.com/introduction/getting-started.html

### Actual Result

The console gets this far and then seems to hang forever:

```
C:\Users\warren>npm install semantic-ui --save

> semantic-ui@2.4.2 install C:\Users\warren\node_modules\semantic-ui
> gulp install

[22:48:17] Using gulpfile ~\node_modules\semantic-ui\gulpfile.js
[22:48:17] Starting 'install'...
[22:48:17] Starting 'run setup'...
? Set-up Semantic UI Automatic (Use default locations and all components)
? We detected you are using NPM Nice! Is this your project folder? C:\Users\warren Yes
? Where should we put Semantic UI inside your project? semantic/
[22:48:21] Finished 'run setup' after 4.61 s
[22:48:21] Starting 'create install files'...
Installing
------------------------------
Installing to semantic/
Copying UI definitions
Copying UI themes
Copying gulp tasks
Adding theme files
Creating gulpfile.js
Creating site theme folder C:\Users\warren\semantic\src\site\
[22:48:22] Starting 'create theme.config'...
Adjusting @siteFolder to:  site/
Creating src/theme.config (LESS config) C:\Users\warren\semantic\src\theme.config

```

Task Managers shows the CPU and disk are idle and so nothing is being done (the process is not just taking a long time).

Deleting `node_modules/semantic-ui/` and trying again does not help.

Deleting `node_modules/semantic-ui/` and selecting different options does not help.

### Version

Latest from npm.

I'm using npm 6.7.0 on Windows 10 Home, Build 17763. npm 6.4 that comes with the latest node LTS release also had the same behavior.

My gulp version is from a recent install, the latest from npm:

```
C:\Users\warren>gulp --version
[22:58:04] CLI version 2.0.1
[22:58:04] Local version 3.9.1
```

### Testcase

N/A

**Comment by hammy2899** [comment] 2019-01-27 14:16
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6641

**Closed by hammy2899** 2019-01-27 14:16 UTC
Labels: Duplicate

**Comment by sailorsamoor** [comment] 2019-08-28 10:03
Hello. The same situation with me, I installed WSL and installed there semantic-ui, then I copied files from WSL dir into Windows place. Will be try.
