### ISSUE TITLE
fluid input not growing

### ISSUE THREAD

**Issue by GhostSlayer** [Semantic-Org/Semantic-UI#2096] opened 2015-04-10 11:14 UTC
http://semantic-ui.com/elements/input.html#fluid

```
<div class="ui fluid icon input">
  <input type="text" placeholder="Search a very wide input...">
  <i class="search icon"></i>
</div>
```

only makes the wrapping div itself span the entire width, the input doesn't grow (see link, it doesn't work there either)

If that's just me, ignore this

**Comment by jlukic** [comment] 2015-04-10 14:15
This was caused by switch to flex, will be fixed in `2.x` if you can hold tight

**Closed** 2015-04-10 15:31 UTC
Labels: Already Fixed
