### ISSUE TITLE
[Label] Improper alignment of some icons on labels

### ISSUE THREAD

**Issue by louwers** [Semantic-Org/Semantic-UI#5619] opened 2017-08-02 12:02 UTC
See the following test case: https://jsfiddle.net/pnj0f4ed/3/

![screenshot_2017-08-02_14-01-48](https://user-images.githubusercontent.com/649392/28872813-2465806e-778b-11e7-96ae-113e1bf60f89.png)

The right icon has a different alignment than the left icon.

**Comment by Banandrew** [comment] 2017-08-02 16:54
Hi @louwers, this pattern is supported only for the `.delete.icon`. This thread is a duplicate of #5328 that I labeled as enhancement initially, but its author decided to close it—you can find a temporary solution there. I’m not sure if it should be a part of the core, though, and will reopen the original thread if you think that it should.

**Closed by Banandrew** 2017-08-02 16:54 UTC
Labels: Duplicate
