### ISSUE TITLE
Vertical divider are broken

### ISSUE THREAD

**Issue by madela** [Semantic-Org/Semantic-UI#4606] opened 2016-09-29 19:58 UTC
Vertical dividers are broken in the last version. You can check it here: http://semantic-ui.com/elements/divider.html

They are aligned to the left. This is happening only in Chrome, Firefox and Safari is ok.

![screen shot 2016-09-29 at 21 56 23](https://cloud.githubusercontent.com/assets/5593359/18969941/9780650c-868f-11e6-801e-140bf61fbf36.png)

**Comment by IonutBajescu** [comment] 2016-09-30 16:35
Yeah, you're right. Unfortunately this is a known issue :( 

I'm closing this as a duplicate of #4342.

**Closed by IonutBajescu** 2016-09-30 16:35 UTC
