### ISSUE TITLE
Danger, the Chinese page in https://semantic-ui.com/globals/reset.html is linked to http://www.semantic-ui.cn, but the content of the site is now a game information suspected of gambling.

### ISSUE THREAD

**Issue by youuycom** [Semantic-Org/Semantic-UI#6792] opened 2019-04-17 08:25 UTC
Danger, the Chinese page in https://semantic-ui.com/globals/reset.html is linked to http://www.semantic-ui.cn, but the content of the site is now a game information suspected of gambling.

**Comment by hammy2899** [comment] 2019-04-17 16:19
duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6736

**Closed by hammy2899** 2019-04-17 16:19 UTC
Labels: Duplicate
