### ISSUE TITLE
Validation in form should validate all fields in Semantic website example

### ISSUE THREAD

**Issue by christoferd** [Semantic-Org/Semantic-UI#6517] opened 2018-08-02 23:48 UTC
### Steps
Go to https://semantic-ui.com/behaviors/form.html
Submit first form

### Expected Result
Expect all field to display validation errors

### Actual Result
The fields that are not in the first column (Gender, Password) do not show errors.

### Version
Semantic UI - 2.3.3

### Testcase
No need, it's on your website with the example source code.

**Comment by andynu** [comment] 2018-08-07 16:11
This is more than a documentation issue. Validation appears to be broken for dropdowns. See the earlier ticket #6026

**Comment by hammy2899** [comment] 2018-08-07 17:35
@andynu Dropdown validation is totally fine, this is a docs issue. https://jsfiddle.net/7zgfj26k/

Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6026

**Closed by hammy2899** 2018-08-07 17:35 UTC
Labels: Duplicate
