### ISSUE TITLE
Sticky topmenu with Safari iOS

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#1739] opened 2015-01-31 06:23 UTC
As seen on official main page http://semantic-ui.com top sticky menu has issues with Safari on iPad or iPhone. 
When scrolling down:
- the Safari bar does not colapse
- the top sticky menu of http://semantic-ui.com does not appear 
- the page is sligjtlly blicking/tearing itself when scrolling
- the top sticky menu appears only when you finish scrolling to the very bottom

See screenshots:
![image](https://cloud.githubusercontent.com/assets/5719547/5987096/ea0a8dd4-a919-11e4-92ca-4a4148473ab2.jpg)
![image](https://cloud.githubusercontent.com/assets/5719547/5987097/ea34f2a4-a919-11e4-8511-6dd8343bf341.jpg)

Compare behavior of e. g. Google desing sprint  page top sticky menu:
![image](https://cloud.githubusercontent.com/assets/5719547/5987101/142ae294-a91a-11e4-9c6f-795869f1e58d.jpg)

**Comment by Basgrani** [comment] 2015-01-31 18:48
Hello, I think this is exactly what happens to me and try to explain here:

https://github.com/Semantic-Org/Semantic-UI/issues/1644

Thanks

**Comment by kvetoslavnovak** [comment] 2015-02-01 05:44
Important concern is that having such an issue on SemanticUI main introduction page does not look good to visitors with iPhones or iPads. 
Anyway Semantic UI is great. Big thank for your hard work.

**Comment by jlukic** [comment] 2015-02-01 18:33
Duplicate of #1644, continue discussion there.

**Closed** 2015-02-01 18:33 UTC
Labels: Duplicate
