### ISSUE TITLE
ui dropdown does not hide when click others dropdown icon of the right

### ISSUE THREAD

**Issue by xiwc** [Semantic-Org/Semantic-UI#3998] opened 2016-05-06 01:34 UTC
First: click the icon open the menu.
![image](https://cloud.githubusercontent.com/assets/8816203/15061941/9cd1769e-136d-11e6-85a3-f426cd62cdd1.png)

Second: click the icon open the menu of other one dropdown.
![image](https://cloud.githubusercontent.com/assets/8816203/15061945/ac17a358-136d-11e6-946e-66ddc1597a8a.png)

**Comment by jlukic** [comment] 2016-05-20 07:06
I can't reproduce this in Chrome, everything seems to be closing correctly. Is there something I'm missing?

Jsfiddle?

**Comment by Ryuno-Ki** [comment] 2016-05-20 21:01
I can confirm on Firefox v46.0 on GNU/Linux. I could not provoke it when the dropdowns open towards top however.

Browser console states:
```
Popup: Popup does not fit within the boundaries of the viewport <div class="max example"> semantic.min.js:16:3861
Popup: Popup does not fit within the boundaries of the viewport <div class="max example"> semantic.min.js:16:292
Popup: Popup does not fit within the boundaries of the viewport <div class="max example"> semantic.min.js:16:29
```
In order to provoke the behaviour I need to hit the `.dropdown.icon` of the second `select` - opening it anywhere else does not reproduce it.

*Selection* select has `class="ui fluid normal dropdown selection multiple active visible"`, while *Without Labels* select has `class="ui fluid multiple search special selection dropdown active visible"` (both are `.active.visible`). I could not provoke it using *Selection* and *Search Selection*.

@jlukic JSFiddle is served via HTTPS, so I cannot load semantic.css/.js (MixedContent Warning).

For reference: [Dropdown examples](http://semantic-ui.com/modules/dropdown.html#/examples).
My resolution is 1366x768.
![semantic-dropdown-bug](https://cloud.githubusercontent.com/assets/3097194/15441747/f5256e16-1edc-11e6-93c5-0b1eb088c8f6.png)

**Comment by xiwc** [comment] 2016-06-13 06:12
@jlukic It can be easily reproduced, when clicking the dropdown icon but other place. It still can be reproduce on my latest Chrome of WIN7 OS.

**Comment by drupalshift** [comment] 2016-06-21 10:33
If you click **exactly on arrow icon** you can reproduce this error , Firefox 47 and Chrome 51.0.2704.103 on Windows

**Comment by zhaoyao91** [comment] 2016-07-11 09:54
![screenshot_20160711-175042](https://cloud.githubusercontent.com/assets/3808838/16726730/4d764816-4790-11e6-9052-245a12904bf4.png)

on my phone (galaxy s7 edage), chrome, it always behaviors like this.

**Comment by jlukic** [comment] 2016-07-31 15:07
Dropdown icon was preventing events from bubbling, meaning other dropdowns couldnt correctly observe the click event to close the dropdown. Fixed

**Closed by jlukic** 2016-07-31 15:07 UTC
Labels: Confirmed Bug
