### ISSUE TITLE
Sidebar creates misterious padded black line

### ISSUE THREAD

**Issue by romuloctba** [Semantic-Org/Semantic-UI#1655] opened 2015-01-18 03:33 UTC
Hey guys.
First, love. Thank you for this awesomeness!

Second, problem. (sorry)

When using sidebar, I open it and it creates a black line in one of the sides of the window. I tried to find where it does, and all i could do was palliatively editing a `.ui.grid+.grid` class. Weird is that if sidebar is not initialized, this black line does not exist.

Here is some code:

```<div class="ui menu icon inverted sidebar">
		<h2>Hey you</h2>
	</div>
	<div class="ui pusher">
		<div class="ui page grid">
			<div class="ui two wide row">
				<div class="ui column">
					<div class="ui header">
						<h1>test <button class="ui button" onclick="$('.sidebar').sidebar('toggle');">Open</button></h1>
					</div>
				</div>
			</div>
		</div>
	</div>```

Just put it inside the `body`with semantic.css and semantic.js enabled and check what happens

In this case the black line comes from bellow.

**Comment by jlukic** [comment] 2015-01-18 07:16
This is probably caused by having padding on `body`

**Comment by romuloctba** [comment] 2015-01-18 16:05
well if you use the html provided above you'll see that without any other css, the situation still happens 
:-(

**Comment by romuloctba** [comment] 2015-01-21 19:30
@jlukic do you think you could test the html I provided (minimum markup to replicate the problem) ?and let me know if it is a bug or just me? 

<small>I m kindda of sad being this thread labelled as Question. See that the html </small>
```html
<div class="ui menu icon inverted sidebar">
  <h2>Hey you</h2>
</div>
<div class="ui pusher">
  <div class="ui page grid">
    <div class="ui two wide row">
      <div class="ui column">
        <div class="ui header">
          <h1>test <button class="ui button" onclick="$('.sidebar').sidebar('toggle');">Open</button></h1> 
          </div>
        </div>
      </div>
  </div>
</div>
```

**Comment by jlukic** [comment] 2015-01-22 17:59
This is due to collapsing margins on pusher

See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/margin_collapsing)

I think i can find a workaround for this. Have to be really careful with using `overflow: hidden` on pusher though, might cause side effects.

**Comment by jlukic** [comment] 2015-01-23 16:57
Should be fixed in `next` using your test case.

**Closed by jlukic** 2015-01-23 16:57 UTC
Labels: Bug
