### ISSUE TITLE
[Dimmer] When useCSS:true Dimmer has not any state class

### ISSUE THREAD

**Issue by notgifted** [Semantic-Org/Semantic-UI#4668] opened 2016-10-19 08:07 UTC
https://jsfiddle.net/ReVolution255/10pce2fu/

Steps:
1. Create modal with settings:

```javascript
blurring: true,
allowMultiple: true,
closable: false,
dimmerSettings: {
 duration: {
  show: 15000,
  hide: 500
 },
 useCSS: false
},
observeChanges: true
```
1. Open modal

Result: dimmer classes not changed ("ui dimmer modals page")

![234e67f2c7d25b1fe0976ffe09ae0a8b](https://cloud.githubusercontent.com/assets/7694939/19510409/23e4b0f2-95f4-11e6-8099-431bc6307267.png)

**Comment by vinayakkulkarni** [comment] 2017-02-20 05:28
It's working for me:

<img width="853" alt="screen shot 2017-02-20 at 10 55 59 am" src="https://cloud.githubusercontent.com/assets/19776877/23113047/403ff7a2-f75b-11e6-828d-82578ce5ab14.png">

[jsFiddle updated example](https://jsfiddle.net/vinayakkulkarni/8g2bc9Ln/
)
PS. if you need centered modal, instead of setting custom alignment using calc(), just use 

```css
#modal1 {
  align-items: center;
  justify-content: center;
}
```

**Comment by vinayakkulkarni** [comment] 2017-02-23 12:59
Closing till OP replies

**Closed by vinayakkulkarni** 2017-02-23 12:59 UTC
Labels: Usage Question

**Comment by notgifted** [comment] 2017-02-23 17:22
Check [dimmer settings](http://semantic-ui.com/modules/dimmer.html#/settings):

className.transition = "transition"

In your jsfiddle <div class="ui dimmer modals page"> has no class 'transition' when transition occurs.

**Comment by Banandrew** [comment] 2017-02-26 22:43
Hi @notgifted, I looked into it, and also couldn’t reproduce; the dimmer properly receives all transition classes. Setting the duration via the dimmer component seems to be messing up the transitions, but I’m assuming that’s why the modal component received its own `duration` property.
