### ISSUE TITLE
[Button] Responsive Size 

### ISSUE THREAD

**Issue by jeremyjohn** [Semantic-Org/Semantic-UI#5206] opened 2017-03-28 00:12 UTC
Please add responsive size support for button.
Something like: 
```
<button class="mini-mobile massive-computer ui button">
  Button
</button>
```

**Comment by Banandrew** [comment] 2017-03-28 14:34
It seems to be a duplicate of #1012.

**Closed by Banandrew** 2017-03-28 14:34 UTC
Labels: Duplicate
