### ISSUE TITLE
[Steps] Evenly Divided Steps

### ISSUE THREAD

**Issue by adrazich** [Semantic-Org/Semantic-UI#1787] opened 2015-02-11 13:46 UTC
In version 1.8.1 the steps don't evenly divide amongst their parent anymore when using numbered steps. They used to fill the entire width.

example: 
![screen shot 2015-02-11 at 8 45 25 am](https://cloud.githubusercontent.com/assets/1614075/6147909/58973bd6-b1ca-11e4-8849-8784c7336777.png)

**Comment by jlukic** [comment] 2015-02-11 16:16
This appears to be a bug caused by switch to `table-cell` for equal height.  One secs

**Comment by jlukic** [comment] 2015-02-11 16:25
Fixed in `next`

**Closed by jlukic** 2015-02-11 16:25 UTC
Labels: Bug
