### ISSUE TITLE
Search submit button not a input element but div

### ISSUE THREAD

**Issue by KeinTrong** [Semantic-Org/Semantic-UI#1693] opened 2015-01-23 09:02 UTC
I'm refer to this : http://semantic-ui.com/elements/input.html#action

I'm using it as a search form but the submit button is a div, not a input field. When I change it to a input field these elements get mess.

Or you have a better solutions ?

**Comment by KeinTrong** [comment] 2015-01-23 09:18
I had search other topics as well but seem like button does not support for "table-cell" display.

**Comment by jlukic** [comment] 2015-01-23 16:40
Duplicate of #793 

Please contribute to the conversation there with a +1 etc.

**Closed** 2015-01-23 16:40 UTC
Labels: Duplicate
