### ISSUE TITLE
Dropdown on change

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5347] opened 2017-05-07 22:27 UTC
Hi,

I want to attach an event to the dropdown that fires basically when anything change inside this component. I want this event to fire when the user:

1) is typing anything (it's a dropdown seach)
2) the user uses the arrow keys to navigate in the options of the select

I cant find anyting related to this here -> https://semantic-ui.com/modules/dropdown.html#/settings

Basically I want to get the first result of the dropdown and set it as a placeholder in the search box so the user knows the best prediction.

**Comment by batata004** [comment] 2017-05-07 22:44
I did a code that works almsot as I wanted BUT FOR SOME REASON semantic UI does not allow me to set placeholder of the input.search.


```
				$("#dropdown_element").find(".search").on(
				
					"keyup",
					function() {
					
						if (   ($("#dropdown_element").find(".item").not(".filtered").length != 0)   &&   ($(this).val().replace(new RegExp(" ","g"),"") != "")   ) {
						
							$(this).attr({placeholder:$("#dropdown_element").find(".item").not(".filtered").eq(0).attr("data-value")});
							
						}
						else{
						
							$(this).attr({placeholder:""});
						
						}
					
					}
					
				);
```


Does anybody knows how can I set the placeholder to the search input inside the dropdown menu?

**Comment by Banandrew** [comment] 2017-05-08 02:28
Hi, I can confirm that this code piece successfully sets the placeholder to be a value of the selected option. I’ll be closing this thread, since it’s a follow-up to the original issue #5336, and we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers.

**Closed by Banandrew** 2017-05-08 02:28 UTC
Labels: Usage Question

**Comment by batata004** [comment] 2017-05-08 13:00
No @Banandrew it does not work at all. The placeholder gets seted WHEN THE USER LEAVES the field (blur effect) AND EVEN THEN the placeholder gets mixed with the "default text" message of the field.

You can see clearly the bug here -> 
![aa](https://cloud.githubusercontent.com/assets/8988923/25805188/286a9090-33d5-11e7-9c97-c417a5026f3c.jpg)

Could you please open this thread and analyze thisb ug?

**Comment by Banandrew** [comment] 2017-05-08 20:40
@batata004 

1. The overlaying issue has been known for a while, I can’t find the exact thread right now, but it does exist. It might be closed, because you can’t reproduce it using vanilla dropdowns, so it’s not an issue with the framework itself, but rather with a particular use case.
2. I checked your code again, and I stand by what I said about it previously, [here’s a video](http://i.imgur.com/FZanl5O.gifv). As you can see, it sets the placeholder; you can’t see the placeholder, because you’re typing into the field—it’s the default browser behaviour for input elements.

**Comment by batata004** [comment] 2017-05-08 21:25
@Banandrew you are 100% correct. I am really sorry for being an idiot. You are correct, I knew the placeholder was being set checking F12 but I was not seeing it. You are correct, in order to see the placeholder the value of the input must be empty. I am really sorry for my stupidity.

So I ask you: how can I make it possible to make the first result item (from the items elements inside the dropdown) be shown with a lighter color behind what user is typing? GMAIL implements this in a very nice way, try to search some email inside gmail (the search box at the top) typing some email account. You will see it autocompletes with a suggestion. Do you know how can I achieve this? Maybe making the "default text" element visible and chaning its content?

**Comment by Banandrew** [comment] 2017-05-09 00:34
@batata004 I honestly don’t have to time to research it, but I think Gmail uses two inputs, one for the actual search, and another for autocompletion—maybe it’s the way to go. I quickly tried it, it kind of works, just needs a couple of tweaks to position the text correctly.

**Comment by batata004** [comment] 2017-05-09 00:41
Thanks man and sorry for taking your time, you are all doing a great job with this library!
