### ISSUE TITLE
(Another) inconsistency with elements size

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#5082] opened 2017-02-24 15:05 UTC
Hi,

I am facing a really really weird bug with elements size with semantic ui. I like so much semantic ui cause when I use big, huge, medium... classes, all my elements get the same height which is great cause the design gets but easier to handle.

BUT I found another bug (in my opinion) with semantic ui and it's weird. It's weird because the same code when executed inside jsfiddle does not produce the error but the EXACTLY same code hosted everywhere else produces the bug. Open these 2 links, please:

https://jsfiddle.net/59azLzyp/

http://quemfazsite.com.br/temp/teste2.php

You will see in the first example all the 4 buttons (3 circular and the one in the right) get the same height. In the second example the 3 circular buttons are a little smaller than the button in the right. You can easily inspect the code and you will see both links above use the exactly same code.

In case you are not wearing glasses I attached a image below of the inconsistency zoomed in.
![bug](https://cloud.githubusercontent.com/assets/8988923/23308281/77a48ba0-fa89-11e6-9e50-d8fac2ea4dd7.jpg)

**Comment by jlukic** [comment] 2017-02-24 20:02
I can't confirm its the cause, but it might either be related to which icon font is served, or whether there is whitespace in your html. (This affects inline block items).

**Comment by batata004** [comment] 2017-02-24 20:29
Both codes are exact the same @jlukic . If it is related to whitespace (which is known for causing this kind of problem) it should affect both examples. Both have the same doctype, encoding, libraries... I wonder what is making this bug to happen, I already tried minifying the code and the problem still happens so we can, respectfully, abort  this whitespace hypoteses .

**Comment by philrykoff** [comment] 2017-03-02 08:57
I have no explanation why, but the root cause is your ancient doctype :smiley: 

If you use '<!DOCTYPE html>', it works.

**Comment by batata004** [comment] 2017-03-02 18:19
Changing doctype did the trick! It's an ancient doctype but many websites still use, I dare to say that more websites use that ancient doctype than "DOCTYPE html".

Anyway, it was easier to change doctype to the one you recommended instead of waiting a fix to this! Thanks @philrykoff thanks a lot!

**Comment by philrykoff** [comment] 2017-03-02 18:24
It would seem that this is the fix. If everything else is the same, there is no other possibility.

**Comment by batata004** [comment] 2017-03-02 18:33
Should I close this? Despite the fix the bug remains for websites that use old doctype. Anyway, I am already pleased with the solution so you decide if you want to close this.

**Comment by philrykoff** [comment] 2017-03-02 18:45
There seems to be consensus about the fact that doctypes do not determine which CSS level can be used (e.g., 3), so I am still not sure why the doctype change fixed the inconsistency.

Yet, if we determine that we need an HTML 5 doctype, we should include that in the docs (e.g. within the "Include in your HTML" section of http://semantic-ui.com/introduction/getting-started.html). Otherwise... what is the root cause?

@jlukic should probably decide. 😉

**Comment by Banandrew** [comment] 2017-08-14 14:34
I missed this issue, and the actual test case is unavailable now, but my guess is browser modes. I don’t think it’s necessary to mention the HTML 5 doctype in the documentation, since `<!DOCTYPE html>` has been a recommended way of enabling standards mode for 2 years now, and it’s a developer’s responsibility to be up to date with industry standards.

I’ll close this for now as resolved.

**Closed by Banandrew** 2017-08-14 14:34 UTC
Labels: Docs Issue

**Comment by batata004** [comment] 2017-08-14 14:36
Yeap using <!DOCTYPE html> works fine, confirmed here. I replaced many of my websites from the old doctype to the new.
