### ISSUE TITLE
Sticky not working in pushable div 

### ISSUE THREAD

**Issue by ptylde** [Semantic-Org/Semantic-UI#5388] opened 2017-05-19 20:09 UTC
Hi, the sticky module is not working if it is inside the 'ui pushable' div. I've made a codepen of the problem. The second sticky card doesn't work as it is inside the pushable div. If you remove the pushable and pusher divs the sticky works as expected.

https://codepen.io/thegreaterpanda/pen/rmqEPw

**Comment by Banandrew** [comment] 2017-05-20 02:31
Hi @ptylde, thank you, but it seems to be a duplicate of #2774—`.pushable:not(body)` ruleset uses `translate3d` that interferes with the sticky component. Please see #1745 for more information.

**Closed by Banandrew** 2017-05-20 02:31 UTC
Labels: Duplicate
