### ISSUE TITLE
The site of http://www.semantic-ui.cn/ was another web, not Semantic-UI

### ISSUE THREAD

**Issue by SongX64** [Semantic-Org/Semantic-UI#6903] opened 2019-11-27 13:26 UTC
Hey man, you should look at http://www.semantic-ui.cn/,  it become something not good....
Look at this.
![image](https://user-images.githubusercontent.com/28941801/69726964-88eb3200-115c-11ea-9f8e-36f5a89d3046.png)
I hope u can check your web.

**Comment by vinayakkulkarni** [comment] 2019-11-27 13:57
Duplicate of #6736

**Closed by vinayakkulkarni** 2019-11-27 13:57 UTC
Labels: Duplicate
