### ISSUE TITLE
[Menu] Colored variations of “.inverted.pointing.menu” should all have a colored pointer

### ISSUE THREAD

**Issue by gluons** [Semantic-Org/Semantic-UI#4846] opened 2016-12-22 08:53 UTC
<img width="363" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/21420132/6b6f6484-c85e-11e6-9466-8fff582e0b81.PNG">

Pointing indicator color in **inverted colored pointing menu** is wrong.

See on [JSFiddle](https://jsfiddle.net/illuminator/293yfxhs/).

**Comment by Cyb3rWarri0r8** [comment] 2016-12-28 23:31
It would appear here:
https://github.com/Semantic-Org/UI-Menu/blob/master/menu.css#L1522
and here
https://github.com/Semantic-Org/UI-Menu/blob/master/menu.css#L1842
would be wear your issues are.. this is just my initial analysis so I could be completely wrong. 

This seems to be where the pointing is defined
https://github.com/Semantic-Org/UI-Menu/blob/master/menu.css#L1809

```css
.ui.pointing.menu .item:after {
  visibility: hidden !important;
}
```
That bit will hide it..
I believe the issue is with the CSS for it not being defined... (Just looking at the repo)
This should fix the issue: 
```css
.ui.inverted.green.three.item.pointing.menu .active.item:after {
  background-color: #3ca83e !important;
  /* color: #3ca83e !important; */
}```

**Comment by Zertu** [comment] 2017-05-22 15:21
Why this bug still here?!!

**Comment by Banandrew** [comment] 2017-05-23 00:40
It’s in the process of being fixed, somebody already opened a PR the other day. Closing the issue as a duplicate of #2355.

**Closed by Banandrew** 2017-05-23 00:40 UTC
Labels: Duplicate
