### ISSUE TITLE
ver.2.3 multiple dropdown not showing hidden input values

### ISSUE THREAD

**Issue by armaganari** [Semantic-Org/Semantic-UI#6280] opened 2018-03-18 09:26 UTC
Hi Jlukic
ver 2.2 ok but, ver.2.3 multiple dropdown not showing hidden input values
```html
<div class="ui dropdown">
  <input type="hidden" name="gender" value="male">
  <i class="dropdown icon"></i>
  <div class="default text">Gender</div>
  <div class="menu">
    <div class="item" data-value="male">Male</div>
    <div class="item" data-value="female">Female</div>
  </div>
</div>
```

**Comment by hammy2899** [comment] 2018-03-18 14:42
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6123

**Closed** 2018-03-18 20:56 UTC
Labels: Duplicate
