### ISSUE TITLE
Pull requests and issues closed by the bot

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#6413] opened 2018-05-28 09:43 UTC
Hi guys,

So i have pull requests that were closed by the github bot and or will be closed due to the fact that they didn't receive any answer from the maintainers of the repo.
I see that my pull requests and many others are fairly simple and clear, but they stay unprocessed.
That will add up to the long queue of pull requests, why not make a decision and choose to merge them or close them ?

**Comment by prudho** [comment] 2018-05-29 06:31
Well, the main issue is that @jlukic seem no longer interested in maintaining this repo anymore, and no one but him can merge pull requests. Maybe @hammy2899 has some powers to move things... or this project is doomed to die or be forked... #6109 must be reopen...

**Comment by hammy2899** [comment] 2018-05-30 11:51
Ok so I see a lot of people have been questioning the state of development for SUI over the past month and believe it or not so have I, I haven't had a response from Jack for about 2 months now and the last time I heard he was quite busy with work (work-related trips etc.). I do see a lot of people care about the project and want to help out.

I have also been quite busy the past month with work but have tried to jump on Github at least once a day to sort through issues and I am hoping I can continue this but I do understand it's not enough since there is no real way to get changes merged.

My plan is, if enough people want to collaborate and form a team for a community fork I will do that this week and will start merging changes for bugs and features. Keep in mind I will be forking with the intent to merge back into this repo if Jack does agree to start active development again. That being said I will keep the fork in the same mindset as Jack for changes etc.

**Comment by brodybits** [comment] 2018-05-30 12:03
I would rather see some more discussion before such a fork. I did not think @jlukic was the only owner. I would vote for more noise and discussion on GitHub and other places such as Twitter and private email until we can get to the bottom of this.

**Comment by prudho** [comment] 2018-05-30 12:20
@brodybits there's a gitter [here](https://gitter.im/Semantic-Org/Semantic-UI) where we can talk about it.

That being said, SUI need to move further, even without @jlukic. This is not the first warning about the lack of maintenance on SUI (see #6109, #4886, #4059 and #3637).

**Comment by shadoWalker89** [comment] 2018-05-30 13:07
Can't jack just give you @hammy2899  admin rights on the repo ? Or maybe transfer it to you if he cannot maintain it.

Let me put this way : 
- I have never enjoyed working with a css framework like i do with semantic.
- When i worked with bootstrap i always need to install plugins for doing various things, i rarely do with semantic.
- Semantic should not depend on one person, there should be a team, see https://github.com/laravel/framework/ there is a community team helping taylor, sorting issues and pull requests for him and that way cut down the number of irrelevant issues and pull requests ... 
i understand that is hard and overwhelming to maintain something as big as semantic, that is why @jlukic should let in more people to help him or pass down the torch if he is no longer interested.

I wish that i had more experience on the inner things of semantic so i can help internally as a member on the repo. 
But i can help as a user of semantic by replying to issues and try to help people.
I think there is a lot of people willing to to the same if the project is still active and not dead.
I really do not want semantic to die, it is such a amazing framework.

**Comment by GammaGames** [comment] 2018-05-30 20:44
This subject has been discussed in 6109, and it sounded like he wanted a system to code review contributors for pull requests, but I'm not sure much work has gone into that. Last time this came up we decided to wait until Jack replied (which he did, and it was a good answer that addressed the worries in the issue).

> Keep in mind I will be forking with the intent to merge back into this repo if Jack does agree to start active development again.

It just seems like, until Jack can come back with a more reliable schedule or a team is added, forking with the intent to merge back is a valid and positive direction. And I would love if the other branch had a tag that prevented the bot from closing issues with a certain tag. The bot is helpful for closing issues that don't need to be open, but closing issues or prs without any feedback from devs can be irritating.

**Comment by arjarn** [comment] 2018-05-31 06:58
In my mind, fork is needed. I'm agree with @hammy2899 dev team should keep mind of SUI. In first, perhaps only bugs fix and if good synergy perhaps extend it ;)

**Comment by brodybits** [comment] 2018-05-31 21:53
In terms of forking @morganbarrett already made a fork in <https://github.com/morganbarrett/Vanilla-Semantic-UI> that replaces jQuery dependency with a Vanilla JS solution. Maybe a good starting point?

**Comment by hammy2899** [comment] 2018-06-01 07:19
@brodybits Since the intent will be to merge back I don't think we should use Vanilla SUI + Jack has commented about removing jQuery multiple times. https://github.com/Semantic-Org/Semantic-UI/issues/1175#issuecomment-59957911 https://github.com/Semantic-Org/Semantic-UI/issues/1175#issuecomment-216063154 https://github.com/Semantic-Org/Semantic-UI/issues/1175#issuecomment-216064266

**Comment by prudho** [comment] 2018-06-04 12:15
People interested in a fork should join us [here](https://discord.gg/UgzHNZF) to talk about.

**Comment by douglasg14b** [comment] 2018-06-06 04:47
The problem with referring to gitter chat or discord is that we can't join in on the discussion, as it happens in spurts, and in-the-moment. The only way a discussion can be held asynchronously from interested parties in many different timezones is somewhere more static, like here.

**Comment by prudho** [comment] 2018-06-06 06:08
@douglasg14b You can also joining us [here](https://github.com/hammy2899/Fomantic-UI) now.

**Comment by GammaGames** [comment] 2018-06-06 14:09
Jack has commented on the matter as well, so it looks like progress will be on pause for a bit anyway: [#6418](https://github.com/Semantic-Org/Semantic-UI/issues/6418#issuecomment-394875430)

**Comment by douglasg14b** [comment] 2018-06-12 18:34
@prudho How do you/we direct new Semantic UI users over to Fomantic-UI for the time being? And  are the Fomantic-UI admins holding themselves to the promise to merge back into Semantic UI in the future? Will Jack allow it to merge back in?

**Comment by prudho** [comment] 2018-06-13 06:46
I'm not sure I can answer all these questions, and it's only my opinion (maybe @hammy2899 would add some words).
> How do you/we direct new Semantic UI users over to Fomantic-UI for the time being?

For now the main goal isn't to got more users, but to find people willing to keep SUI alive. That's why we don't talk to much about it. Keep in mind that the main purpose of this fork is to be merged back with SUI.
> And are the Fomantic-UI admins holding themselves to the promise to merge back into Semantic UI in the future?

We will do everything for.
> Will this project have assurances to avoid the same problems we've seen here?

That kind of thing cannot be predicted, but there won't be only one maintainer on board. We want people to help us, new maintainers which fix issues and bring SUI new features, and for that, we will give some powers to them.
> Will the name stay as "Fomantic-UI"?

I don't know. I personnaly dislike the Fomantic name, but it's not the time to start thinking about a new name.
> How will users be directed to it?

I don't think about that, yet.

**Comment by hammy2899** [comment] 2018-06-13 07:28
@prudho answered this pretty well but I just want to add a few words to the matter.

> How do you/we direct new Semantic UI users over to Fomantic-UI for the time being?

As @prudho said at this moment that isn't our goal, our current goal is to get enough reliable contributors to make regular updates to the framework. As for merging back that is not 100% promissed it will happen since this will after all be up to @jlukic. However we are managing the project as if it was to help with the merge if it does happen.

> are the Fomantic-UI admins holding themselves to the promise to merge back into Semantic UI in the future?

As the FUI owner I can tell you that if @jlukic starts active development on Semantic-UI again and agrees to merge them I will 100% do so.

> Will this project have assurances to avoid the same problems we've seen here?

As @prudho said we are gathering a team of contributors and some of which will have privileges allowing them to make updates, therefore if someone does go quite there is always someone to make updates and manage the project.

> Will the name stay as "Fomantic-UI"?

I choose the name "Fomantic-UI" so that it was distinct enough so people knew it was something different and so it would help in discussion and eliminate confusion. If the fork does merge back it will becoming "Semantic-UI" again but as long as the project is a fork it will be called "Fomantic-UI".

> How will users be directed to it?

As mentioned above that isn't our main goal right now nor has it been discussed. That being said that doesn't mean I am not thinking of ways to alert people to the fork.

---

As a SUI user I don't want the project to die out and with its current state that is where it's heading that is why I created this fork. I can assure you if something was to happen making me unable to maintain the fork I will had ownership over to someone else allowing the fork to live on as long as need be.

If anyone is wanting to checkout the fork you can find it here https://github.com/hammy2899/Fomantic-UI and you can join in with the discussion here https://discord.gg/YChxjJ3.

If anyone wants to help out by contributing please feel free to join the Discord and talk to us, we welcome everyone and anyone 😄

**Comment by batata004** [comment] 2018-08-15 13:05
People on Github always surprises me. So good fellows around here. I just came to know about Fomantic today! I work with semantic for as long as almost 3 years on hundreds of small websites. I had to deal with nasty problems regarding so many bug with semantic that it almost drove me crazy.

Take for example the issue with modals/scrolling. I reported a bug almost 2 years ago and after long discussion on many other threads that I followed, it still remains broken. And even worse, on the latest Sematnci UI version if you use modals you will break entirely the scrolling on your page. This bug that I reported 2 years ago got even more disturbing with the lastes verion -> https://github.com/Semantic-Org/Semantic-UI/issues/6449

I think that if @jlukic has no self respect for him nor respect for the commnunity, he should pass the torch on to more active devs like @hammy2899 It's a total disrespct with the users and community if you provide a broken library it hundreds and hundreds of KNOWN BUGS, manny with then with already proposed fix. Unfortunately those fixes dont get merged into the master.

From now on I will start using fomantic and I just did the migration on 3 websites right now and it worked like A CHARM. Super simple.

PEOPLE should be told about the fomantic. I just learned from it today morning. I should have learned from it months ago if it was better shared. Fomantic is awesome and kuddos for the devs behind it!

**Comment by douglasg14b** [comment] 2018-08-15 21:45
@batata004  More people might know about Fomantic if it was an actual fork and showed up as such on Github :/

Not sure why it isn't. If Semantic UI finishes dying, the number of people that will up and leave and never hear about the community fork will be just as bad as semantic dying by itself. Which worries me.

**Comment by hammy2899** [comment] 2018-08-15 22:33
@douglasg14b @batata004 I can confirm FUI is a community fork of SUI, please tell me what makes you think it isnt a fork so we can fix that.

As for speaking to Jack, I messaged him a few times a couple months ago and never got a response. Me and a few other people are starting to think that he is "ditching" the project. The last we heard of him he said that he was trying to get funding which might and probably will be true but that does not explain his absence for so long, that is the main reasons we started the fork.

**Comment by nasatome** [comment] 2018-08-15 23:07
I noticed that @jlukic does not appear in these areas, @hammy2899 could confirm it? more than 30-40 days? :(,
We could create a new ISSUE with the title: "[SEMANTIC UI DEV IS TEMP STOPPED] FOR NEW ISSUES GO TO FORK FOMANTIC UI" in capital letters to get attention. and in that thread explain a summary of the situation. not everyone can take the time to read these threads, a summary would not be bad.

once @jlukic returns the thread is removed and merged again (if so decided) the fork of [Fomantic:](https://github.com/hammy2899/Fomantic-UI)  https://github.com/hammy2899/Fomantic-UI

this to encourage the community to participate in the new fork, and support with PR, When one person observes a project and notes that the PRs are never accepted, the community tends to stop participating and abandon the project, that would be the worst for everyone :( that people see activity in FomanticUI and accept (obviously approved) the PR, it would be great for the community.

At least that is my thought, I do not know what others think?

**Comment by hammy2899** [comment] 2018-08-16 08:29
Jack doesn't seem to have any activity with SUI anymore and as I have mentioned I haven't heard from him in months (last response was March 18th, 151 days as of writing this).

As for creating an issue to get peoples attention, my opinion is that would be rude and would look as if we were taking over the project and that's not what we are trying to do. However, I do agree that we need to do something to get the fork noticed.

I do agree with your comment about people noticing PR's not being merged leading to people abandoning I think part of the problem is because there is so many and with no one who can merge and make releases apart from Jack this will continue to be a problem since we can't just close them.

---

I made an FAQ for FUI https://github.com/hammy2899/Fomantic-UI/blob/beta/faq.md If you have any other questions I encourage you to join the [Discord](https://discordapp.com/invite/YChxjJ3) and we will be happy to respond.

**Comment by GammaGames** [comment] 2018-08-16 14:08
I just want to point out that the last release was on July 8th, a little over a month ago. I do think that Fomantic is a good idea though, at least to keep progress going until we can hopefully get some community maintainers with proper access.

**Comment by batata004** [comment] 2018-08-16 23:14
Just one thing that I would recommend to Fomantic: would it be possible to add it to a CDN (like cdnjs.com)? Cause I use a lot CDN in all my projects, I always embedded semantic ui from CDNJS and if I can help into putting Fomantic there I am here to do what you need.

**Comment by hammy2899** [comment] 2018-08-17 18:25
@batata004 We plan to add fomantic to cdnjs on our next release.
@douglasg14b When a community forks a project a GitHub fork isn't the best option since you can't open issues and pull requests hence the repo. We have recently moved the repos to a new org https://github.com/fomantic.

Can we also keep this issue on topic. If you have any questions about fomantic feel free to open an issue on the [fomantic repo](https://github.com/fomantic/Fomantic-UI) or join our [discord](https://discordapp.com/invite/YChxjJ3).

**Comment by batata004** [comment] 2018-09-02 18:53
Freaking unbeliveable... this library is ditched. I really hope Fomantic gets updated to CDNJS and JSDELIVR so I can stop opening Semantic UI looking for problems to be solved. The last update of semantic ui has so many terrible bugs (like the scrolling one and others related to flex) that didnt happen before. @hammy2899 I will keep an idea on cdnjs as soon as it appears there I will move my websites to fomantic!

**Comment by dreaming-augustin** [comment] 2018-09-03 06:55
The tone of the previous comment is unacceptable. And since there has been a flurry of similar negative comments in various issues (some of which referenced above), I couldn't help but step in, and, as a happy user who has not contributed much if at all, I want to at least express (again) my gratitude to past and current contributors.

May I suggest the following blog entries and wiki articles:

My gratitude to all Semantic-UI contributors:
https://linux.overshoot.tv/blogs/augustin/my_gratitude_all_semantic_ui_contributors 
Hierarchy of contribution in Open Source:
https://linux.overshoot.tv/blogs/augustin/hierarchy_contribution_open_source 
Feeling of Entitlement in Free and Open-Source Software:
https://linux.overshoot.tv/wiki/feeling_entitlement_free_and_open_source_software

**Comment by dreaming-augustin** [comment] 2018-09-03 06:58
The topic of this issue is officially: "Pull requests and issues closed by the bot". This was indeed a bad move and  shadoWalker89 was justified in raising this issue. However, as far as I am aware, Jack admitted (elsewhere) that using the bot was unfortunate and has disabled it quite a while ago. 

@hammy2899 or @shadoWalker89 : do you have the necessary permission to set this issue as fixed?

**Comment by hammy2899** [comment] 2018-09-03 07:09
@dreaming-augustin I don't agree that this issue is fixed, the bot closed a lot of issues which should still be open and until we sort out that "damage" I don't think we can close this issue.


**To all: I will say again please keep this issue on topic.**

**Comment by dreaming-augustin** [comment] 2018-09-03 07:17
Oh, I see. Good point!

**Comment by hammy2899** [comment] 2018-09-03 07:38
@dreaming-augustin I do have permissions but I don't want to go through and just reopen a load of issues without it being talked through because 60% of the issues which are open still probably could be closed so reopening a load of issues would only cause even more problems with managing the project.

**Comment by shadoWalker89** [comment] 2018-09-03 09:04
@dreaming-augustin when i opened the issue the bot was still active
I'll leave closing the issue to @hammy2899 cuz people need a way to discuss the semantic current state and this issue already have some feedback from the community and messages that maybe people need to see like the ones about fomantic

If semantic is dying and is going to perish at least they have the right to hear about fomantic

**Comment by dreaming-augustin** [comment] 2018-09-03 10:00
@shadoWalker89 I know it was still active when you did. I am very sorry, but you misunderstand me. Please read the 3 linked articles. Either you replied to me without at least taking a peek, or you failed to understand the main point. I said nothing against yourself nor against Fomantic-UI, much to the contrary! :)  The now thankfully revoked use of the stale bot was going against the very philosophy expressed in the post: "Hierarchy of contribution", and, as expressed above, I'm happy you helped putting a stop to it, as I am very happy for Fomantic and the very valuable work done by Hammy.  But when random users who have contributed nothing make barely veiled disparaging comments against Jack, like the user I was replying to, I'll speak out in Jack's defence. Without Jack, there'd be no Semantic-UI, and without Semantic-UI, there'd be no Fomantic-UI. Jack made a gift of his work and of his vision, and released everything under a FLOSS license, which is what allows for the fork in the first place. And if Jack does not come back, I'll soon be a very happy and equally grateful Fomantic-UI user. 

with regard to to closing this issue, Hammy already replied, and he made a good point, so there is no argument there either. :)

**Comment by shadoWalker89** [comment] 2018-09-03 11:04
@dreaming-augustin I'm not offended by what you said. Sorry if gave you that impression :D

I'm against negative comments about jack and blaming him, in fact jack owes us nothing. 
I said it before and i'm saying it again semantic is the best css framework i have ever worked with and we all need to thank jack for that. 
But there is difference between blaming jack and letting the project die.

If jack is not able to work on project anymore and not interested in maintaining it, he should just pass the torch.
I mean when Steve jobs died, apple didn't shut down.
There is a huge number of developers and projects in production that depend on semantic, we can't just let semantic die.

I really hope that jack comes back

**Comment by dreaming-augustin** [comment] 2018-09-03 11:51
@shadoWalker89 I agree with every single statement you made :)

**Comment by jlukic** [comment] 2018-09-04 15:56
The bot was a community suggestion to handle the fact that I can't keep track of all community posts. It turns out was probably a bad idea so we disabled it.

I've tried to say this elsewhere, but just to re-iterate, maintenance responsivity/expediency aside, Semantic UI and the general problem of standardizing web UI is still my primary life goal.

**Closed by jlukic** 2018-09-04 15:56 UTC
Labels: Discussion

**Comment by johntd54** [comment] 2020-05-29 08:11
https://github.com/Semantic-Org/Semantic-UI/branches
I saw that the active branches are updated 3 days ago by @jlukic, will the project revive :) ? 

![image](https://user-images.githubusercontent.com/35283585/83236586-f173a400-a1bd-11ea-8e79-371777ac0d68.png)

**Comment by GammaGames** [comment] 2020-05-29 16:13
Looks like he's merged a couple requests related to build dependencies and a bug. Even left some comments!

![image](https://user-images.githubusercontent.com/7832163/83281145-e0fb0380-a194-11ea-8332-86b78c552cb0.png)

**Comment by douglasg14b** [comment] 2020-05-29 19:11
I wonder what will happen in relation to Fomantic-UI which has been moving forward for the last couple years, and are working on a rewrite to better support modern frameworks?
