### ISSUE TITLE
Youtube iframe not working when URL (YouTube ID) contains "-" (Hyphen)

### ISSUE THREAD

**Issue by jiwonbest** [Semantic-Org/Semantic-UI#3837] opened 2016-03-15 21:10 UTC
Hi, 

Is this Semantic UI issue that YouTube iframe doesn't work? (See the Semantic website: http://semantic-ui.com/modules/embed.html#/definition, notice that YouTube doesn't work).

This happens to our app as well.

**Comment by IonutBajescu** [comment] 2016-06-09 18:08
It doesn't look like an issue related to semantic. That video was simply deleted from youtube.  

We should probably look into changing it to one that works so I won't create confusion. I'll leave this open until we change the youtube link. 

![2taalfr](https://cloud.githubusercontent.com/assets/5365516/15940772/709fa74e-2e75-11e6-9309-946fc8e43ff6.png)

**Comment by jiwonbest** [comment] 2016-06-09 20:52
Hi, the problem is most likely related to Semantic UI. 

It says the video is no longer available because Semantic can't read URL whenever there is "-" (hyphen) in YouTube URL, and it ends up showing the video without the full URL. (anything after "-" is not included for some reason)

This has been more than 2 months. Is there anyone in Semantic team trying to fix this issue?

**Comment by Banandrew** [comment] 2017-02-04 08:30
I was unable to reproduce the issue with hyphens, and tried all possible ways of initialization. Please follow [this JSFiddle](http://jsfiddle.net/Banandrew/cjz33eg9) to see it working. It’s been half a year, maybe it was fixed, maybe it was never an issue—I’m closing it as expired.

**Closed by Banandrew** 2017-02-04 08:30 UTC
Labels: Docs Issue
