### ISSUE TITLE
Add more icon support to Rating 

### ISSUE THREAD

**Issue by mrcasablr** [Semantic-Org/Semantic-UI#6710] opened 2018-12-13 07:41 UTC
## Feature Request
Rating component limits icon use to star and heart icon only. Supporting any icon will improve it's usage in many scenarios even for rating too (smiley icon for customer success, thumbs-up icon etc)

### Problem description
I'm building a travel portal where I need to request users for number of users, number of bags they are carrying.  Instead of providing a input field or a select dropdown, its easy for them to click the rating component with the number of such items. It's very intuitive and fast. In this case I would like the icons to be replaced with a user icon and for the second input with a luggage or a bag icon.

### Proposed solution
Allow any icon to be used for rating icon

**Comment by hammy2899** [comment] 2018-12-13 08:35
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/2399

**Closed by hammy2899** 2018-12-13 08:35 UTC
Labels: Duplicate

**Comment by lubber-de** [comment] 2019-01-05 17:08
Available since [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) 2.7.0
https://fomantic-ui.com/modules/rating.html#icon
