### ISSUE TITLE
[Label] label icon problem

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [Semantic-Org/Semantic-UI#5446] opened 2017-06-07 09:27 UTC
why only delete icon work in `label` class ?

```
<a class="ui label">
  <i class="mail icon"></i>
  Mail
</a>
<a class="ui label">
  Tag
  <i class="delete icon"></i>
</a>
```
the below code not working correctly.
```
<a class="ui label">
  <i class="user icon"></i>
  Mail
</a>
<a class="ui label">
  Tag
  <i class="alarm icon"></i>
</a>
```

**Comment by Banandrew** [comment] 2017-06-07 13:57
Hi @abolfazl-ziaratban, there’s no particular reason for that. This thread is a duplicate of #5328 that I labeled as enhancement, but its author decided to close it; I also posted a solution there. I’m not convinced that it should be a part of the core, though, but I’ll reopen the original thread if you think that it should, and the maintainer will take a look.

**Closed** 2017-06-07 13:58 UTC
Labels: Duplicate
