### ISSUE TITLE
[Label] - colored basic label has been full covered by background

### ISSUE THREAD

**Issue by johnull** [Semantic-Org/Semantic-UI#6527] opened 2018-08-07 16:31 UTC
**Steps to Reproduce**
1. nothing to do just use the latest release code, colored basic label should have a white font color but now covered by background color.

**Expected**
The Label should do this
![PsYCm6.png](https://s1.ax1x.com/2018/08/08/PsYCm6.png)

**Result**
The Label does not do this
![PsJjfJ.png](https://s1.ax1x.com/2018/08/08/PsJjfJ.png)
**Testcase**
(fork this to get started)
http://jsfiddle.net/rduvhn8u/1/

**Comment by hammy2899** [comment] 2018-08-07 17:37
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6439

**Closed by hammy2899** 2018-08-07 17:37 UTC
Labels: Duplicate
