### ISSUE TITLE
Incorrect exhange icon in v2.3.0

### ISSUE THREAD

**Issue by maksis** [Semantic-Org/Semantic-UI#6175] opened 2018-02-20 10:25 UTC
https://semantic-ui.com/elements/icon.html:

![image](https://user-images.githubusercontent.com/5640804/36418874-e1dfb8f2-1638-11e8-8e08-104081419d55.png)

https://fontawesome.com/icons?d=gallery&q=exhange:

![image](https://user-images.githubusercontent.com/5640804/36418907-0689bc52-1639-11e8-88b4-001d02e64c6d.png)

**Comment by hammy2899** [comment] 2018-02-20 10:43
I can confirm this, I will try and get a fix for this today

**Comment by GammaGames** [comment] 2018-02-20 15:10
It looks like the arrows alternate horizontal and vertical are email icons as well

![image](https://user-images.githubusercontent.com/7832163/36431649-54b58574-1615-11e8-8c6c-409ecb040ce0.png)

![image](https://user-images.githubusercontent.com/7832163/36431556-2a070ad2-1615-11e8-8bbc-0816be381e70.png)

**Comment by jlukic** [comment] 2018-03-19 00:50
This is fixed in `2.3.1`, thanks for patience

**Closed** 2018-03-19 00:50 UTC
Labels: Confirmed Bug
