### ISSUE TITLE
[Dropdown] onChange doesn't fire if value is 0

### ISSUE THREAD

**Issue by celsworth** [Semantic-Org/Semantic-UI#2436] opened 2015-06-22 01:21 UTC
I'm using Dropdown for a selection that involves a zero value, amongst other things. I have an onChange callback attached to it, and noticed that it doesn't trigger if the zero is selected first.

Try this: http://jsfiddle.net/e4y2Lpcr/2/

After loading the page, select 'One' - the callback fires and logs to console. Now reload the page and select 'Zero' - no callback. It does fire if you select One then Zero.

I believe this is due to the following: https://github.com/Semantic-Org/Semantic-UI/blob/next/src/definitions/modules/dropdown.js#L2046

Because `0 == ""` is `true` in Javascript. Would this check be better as `===`, so a 0 value is recognised as a change from the empty default value? I note that a little further down, there is an `!==` check rather than `!=`, so it would seem to make sense to use `===`.

**Comment by jlukic** [comment] 2015-06-22 01:39
Fixed in next, just hold tight.
http://jsfiddle.net/e0up2cp6/

**Comment by jlukic** [comment] 2015-06-22 01:42
Should probably be `===`. I'll review tomorrow

**Comment by jlukic** [comment] 2015-06-23 21:52
Caused by this evaluating to `true`
```javascript
(0 == '')
```

Using `===` equality will still cause onChange on reselection since the types will be different. Swapped comparison to use string value, since input will always store value as a string.

**Closed** 2015-06-23 21:52 UTC
Labels: Confirmed Bug
