### ISSUE TITLE
[Popup] Should show up close to its element, not at the bottom

### ISSUE THREAD

**Issue by ihpar** [Semantic-Org/Semantic-UI#5549] opened 2017-07-16 22:26 UTC
With V.2.2.11, when scrolling down and keeping the element which has a popup at the top of view-port, its popup shows up at the bottom of view-port.

OS: W10
Browser: Chrome 59
Test page: https://semantic-ui.com/modules/popup.html

Please see the attached screenshot.
1 is the element hovered, 2 is the popup of the element showing up in bottom.
![pubug](https://user-images.githubusercontent.com/26081641/28251831-79472fa6-6a8e-11e7-963e-131251beb53f.png)

**Comment by Banandrew** [comment] 2017-07-28 04:32
I think it’s also important to look at issues that I marked as a duplicate of this one in case they’re not.

**Comment by jlukic** [comment] 2017-07-28 14:11
I'll look at this over the weekend

**Comment by jlukic** [comment] 2017-08-07 01:14
This was an issue with how `$offsetParent` was changed. Fix incoming

**Closed** 2017-08-07 01:14 UTC
Labels: Confirmed Bug, High Priority
