### ISSUE TITLE
Dropdown onChnage does not fire after init

### ISSUE THREAD

**Issue by gewaking** [Semantic-Org/Semantic-UI#3843] opened 2016-03-17 23:44 UTC
> $("#MyList").dropdown({
>     onChange: function(value, text) {
>         console.log("a");
>     }
> });

```
<div id="MyList" class="ui dropdown item"> Export <i class="dropdown icon"></i>
  <div class="menu">
    <div data-value="1" class="item">Item 1</div>
    <div data-value="2" class="item">Item 2</div>
  </div>
  <input type="hidden" name="item">
</div>
```

**Comment by JakeAlmer** [comment] 2016-04-02 03:38
looks like a duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/3744

**Comment by jlukic** [comment] 2016-04-04 00:16
`forOnInit` is a setting for dropdown.
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L3252

**Closed** 2016-04-04 01:52 UTC
Labels: Usage Question
