### ISSUE TITLE
[Sidebar] Sidebar left fixed menu (toggle) + top fixed menu

### ISSUE THREAD

**Issue by romanmuska** [Semantic-Org/Semantic-UI#4386] opened 2016-08-03 21:25 UTC
Hello everyone,

i have a top fixed menu which is full size in width and i want to have a left sidebar which open/close on button under this top fixed menu. It works nice when i dont set context in sidebar but on open it also moved top fixed menu to right because the context of sidebar is default set up on BODY. When i use context it works fine that the sidebar toggling under top fixed bar but when i scrolling context this sidebar isnt fixed ... Can someone help me with that?... Sorry for my bad english. Thanks

**Comment by morenoh149** [comment] 2016-08-24 22:30
I'm seeing this as well. The docs say http://semantic-ui.com/modules/sidebar.html#/usage under `Using Fixed Content` to place the fixed menu as a sibling of the sidebar. But for me this doesn't work with a fixed menu at the bottom.

I think it's because the parent of both the sidebar and the menu gets a `pushable` class and this performs a css transform. When css transform happens, position: fixed children get positioned relative to the transformed element. So the menu appears at the bottom but does not keep scrolling with the viewport. Thoughts?

**Comment by Banandrew** [comment] 2017-02-13 18:31
Hi @romanmuska, the issue is quite old, and I’ll be closing it as a usage question, but if you think it’s an actual problem with the framework, or you’d like to propose a specific feature request—feel free to provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) (you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln)), and someone will reopen it.

**Closed by Banandrew** 2017-02-13 18:31 UTC
Labels: Usage Question
