### ISSUE TITLE
installing semantic-ui in aurelia fails and return errors

### ISSUE THREAD

**Issue by mfarahats** [Semantic-Org/Semantic-UI#5021] opened 2017-02-15 01:22 UTC
i tried to install semantic ui in my aurelia project using npm but the installation process failed so i installed new aurelia project and tried to install semantic ui agian to figure out if it's general problem or not and that what i have got

```
D:\ui-test>npm install semantic-ui --save
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN excluding symbolic link tests\withsymlinks\.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests\withsymlinks\bar.txt -> ../shown/bar.txt
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN excluding symbolic link tests\withsymlinks\.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests\withsymlinks\bar.txt -> ../shown/bar.txt
npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> semantic-ui@2.2.7 install D:\ui-test\node_modules\semantic-ui
> gulp install

[03:02:46] 'install' errored after 1.97 s
[03:02:46] TypeError: gulp.hasTask is not a function
    at D:\ui-test\node_modules\run-sequence\index.js:19:22
    at Array.forEach (native)
    at verifyTaskSets (D:\ui-test\node_modules\run-sequence\index.js:13:11)
    at runSequence (D:\ui-test\node_modules\run-sequence\index.js:92:2)
    at Gulp.module.exports (D:\ui-test\node_modules\semantic-ui\tasks\install.js:452:1)
    at module.exports (D:\ui-test\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\ui-test\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\ui-test\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\ui-test\node_modules\orchestrator\index.js:134:8)
    at D:\ui-test\node_modules\semantic-ui\node_modules\gulp\bin\gulp.js:129:20
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.2.7 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.7 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ui-test\npm-debug.log
```

**Comment by mfarahats** [comment] 2017-02-15 02:21
i found similar issue [#4374](https://github.com/Semantic-Org/Semantic-UI/issues/4374)
i tried to install `gulp` globally but it didn't work too
about trying to modify `node_modules/semantic-ui/tasks/install.js` i can't, the installation rollback and delete the package.
actually i could successfully install semantic-ui in empty folder!

**Comment by vinayakkulkarni** [comment] 2017-02-15 08:56
`npm ERR! Make sure you have the latest version of node.js and npm installed.`

Can you tell which version of node and npm you have?
`npm -v`
`node -v`

**Comment by mfarahats** [comment] 2017-02-15 09:12
node v6.9.1
npm  v4.1.1

**Comment by sondr** [comment] 2017-02-15 11:02
I think the problem is your local version of gulp. The gulp.task method has som breaking changes from v3 => v4. If you use 3.9.1 it will probably work.

I don't think aurelia will build with gulp v3 if you're using the aurelia-cli though, so it might be a pickle.

**Comment by vinayakkulkarni** [comment] 2017-02-17 11:14
@mfarahats : did you try @sondr's solution? downgrading your local gulp to 3.x?

**Comment by vinayakkulkarni** [comment] 2017-02-17 11:16
Also, seems like this is an issue with gulp & aurelia and not the issue with the SUI framework, closing till it gets new replies.

🍻

**Closed by vinayakkulkarni** 2017-02-17 11:16 UTC
