### ISSUE TITLE
Labeled buttons style

### ISSUE THREAD

**Issue by hamedsabzian** [Semantic-Org/Semantic-UI#6522] opened 2018-08-06 11:41 UTC
class="... basic [color] ... label" not work, and the element filling.

### Version
2.3.3

### Testcase
https://semantic-ui.com/elements/button.html#labeled

**Comment by hammy2899** [comment] 2018-08-06 11:45
Duplicate of #6439

**Closed by hammy2899** 2018-08-06 11:45 UTC
Labels: Duplicate
