### ISSUE TITLE
dropdown with remote selection menu content: 'clear' and 'set exactly' remove placeholder

### ISSUE THREAD

**Issue by vst9** [Semantic-Org/Semantic-UI#3861] opened 2016-03-23 11:30 UTC
I'm creating a dropdown using the apiSettings.url member, with a static placeholder text. When I call either dropdown('clear') or dropdown('set exactly'), in addition to doing what they're supposed to - they also remove my placeholder text. Could this be the desired behaviour?

The issue is demonstrated here: http://jsfiddle.net/11coy51r/3/

Either click the 'set exactly' button and then delete the value added, or type any artist name (from Spotify's catalog), select it, and then click clear. Both result in an empty dropdown input box, without the previously visible placeholder.

_Bonus question_:

I had a really hard time (and arguably have failed miserably) producing a simple demo for this issue, mainly because of the 'set exactly' part. So I'm wondering, am I missing something there? Is there a better way of using 'set exactly' on a remote contents dropdown, other than manually adding the selection items to the menu before setting the selected values?

**Comment by jlukic** [comment] 2016-03-25 06:10
Thanks this is pretty clear, I'll investigate soon.

**Comment by philrykoff** [comment] 2017-03-02 10:49
Cannot reproduce anymore with the provided JSFiddle. Probably fixed in between.

**Closed** 2017-03-02 11:54 UTC
Labels: Already Fixed
