### ISSUE TITLE
BUG WITH SCROLLING

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#6486] opened 2018-07-18 12:58 UTC
Hi,

I've been always a serious fan of semantic ui! It's amazing! But in the latest version 2.3.3 the scrolling of the page is not appearing on Chrome in Android.. When I replace 2.3.3 to 2.3.1 the bug disappears completely.

Take a look at this page -> https://www.sitepor500.com.br

The semantic ui is 2.3.1. When I upgraded the CSS and JS to 2.3.3 the scrolling of the page stopped working on chrome in android (I tested on 7 and 8 version of android).

**Comment by ColinFrick** [comment] 2018-07-18 13:04
Duplicate of #6449

**Closed** 2018-07-18 14:42 UTC
Labels: Duplicate
