### ISSUE TITLE
Bug dropdown in new version 2.2

### ISSUE THREAD

**Issue by johndiego** [Semantic-Org/Semantic-UI#5712] opened 2017-08-28 02:14 UTC
![deepinscreenshot20170827231222](https://user-images.githubusercontent.com/18476845/29756866-cf7e76da-8b7d-11e7-9af4-794b3e81721b.png)

**Comment by Banandrew** [comment] 2017-08-28 19:06
Hi @johndiego, I can’t seem to reproduce, could you please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md)? You can fork [this JSFiddle](https://jsfiddle.net/ca0rovs3/).

**Comment by johndiego** [comment] 2017-08-28 23:27
See link https://jsfiddle.net/joediego/m2o1tna1/3/

In the link that I am describing works normally but in my machine does not work, and this happened after the update

**Comment by johndiego** [comment] 2017-08-28 23:31
I found the problem, this occurs in the decrypted version in the minified file

 /*
 * # Semantic UI - 2.2.11
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *

**Comment by Banandrew** [comment] 2017-08-29 20:14
@johndiego I’m a bit confused, did you fix it on your machine?

**Comment by vinayakkulkarni** [comment] 2017-09-07 09:46
Closing this as it has been over a week since OP replied.

**Closed by vinayakkulkarni** 2017-09-07 09:46 UTC
Labels: Needs Test Case

**Comment by nebrelbug** [comment] 2017-11-19 03:59
This same thing happens to me! I'm not sure why it's happening! Could someone please help??? Thanks!

**Comment by nebrelbug** [comment] 2017-11-19 04:00
@johndiego Could you describe how you solved the problem?

**Comment by nebrelbug** [comment] 2017-11-19 04:02
It works fine on CodePen, but when I run it from my Windows computer it doesn't work. Everything else works but this; I have the exact same code on CodePen and it works perfectly.
