### ISSUE TITLE
[Gulp] Core dump during `gulp build-css`

### ISSUE THREAD

**Issue by SpaceboyRoss01** [Semantic-Org/Semantic-UI#6630] opened 2018-10-16 21:16 UTC
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://www.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI
      SO - https://stackoverflow.com/questions/tagged/semantic-ui?sort=votes

✔ Enhancements → Be specific. Assume backwards compatibility is a necessity. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable due to backwards compatibility or CSS limitations.

### Steps
Run `gulp build-css`

### Expected Result
Not crash

### Actual Result
```
[14:11:42] Using gulpfile ~/SherwoodArch/src/ide/src/libs/semantic/gulpfile.js
[14:11:42] Starting 'build-css'...
Building CSS

<--- Last few GCs --->

[32646:0x27d4be0]    91010 ms: Mark-sweep 1419.7 (1543.0) -> 1419.6 (1543.0) MB, 1339.0 / 0.0 ms  allocation failure scavenge might not succeed
[32646:0x27d4be0]    92732 ms: Mark-sweep 1419.6 (1543.0) -> 1419.6 (1525.0) MB, 1720.3 / 0.0 ms  last resort 
[32646:0x27d4be0]    94580 ms: Mark-sweep 1419.6 (1525.0) -> 1419.6 (1523.5) MB, 1846.8 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2bb1876a9891 <JS Object>
    2: copyArray [/home/spaceboyross/SherwoodArch/src/ide/node_modules/less/lib/less/utils.js:~24] [pc=0x14894f493b9f](this=0x149f83a5f7d1 <an Object with map 0x2c2cf3c9d169>,arr=0x30dd7c1ff409 <JS Array[8245]>)
    3: visitImport [/home/spaceboyross/SherwoodArch/src/ide/node_modules/less/lib/less/visitors/import-visitor.js:~38] [pc=0x14894f46d4d1](this=0x150730c7cf89 <an ImportVisitor with map...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [gulp]
 2: 0x1363f0c [gulp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [gulp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [gulp]
 6: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 7: 0x14894ed0437d
Aborted (core dumped)
```

### Version
2.4.1

**Comment by hammy2899** [comment] 2018-10-17 07:07
At first it might not seem a duplicate but all these new gulp problems are related to the recent gulp changes.

Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6622

**Closed by hammy2899** 2018-10-17 07:07 UTC
Labels: Duplicate
