### ISSUE TITLE
npm istall error

### ISSUE THREAD

**Issue by simkepal** [Semantic-Org/Semantic-UI#5044] opened 2017-02-21 09:33 UTC
Hello, when installing the semantic ver. 2.2.8 i get this error

module.js:472
    throw err;
    ^

Error: Cannot find module 'wrench'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/simke/Work/gar-ng4/node_modules/semantic-ui/tasks/install.js:37:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
gar-ng4@0.0.0 /Users/simke/Work/gar-ng4

**Comment by Banandrew** [comment] 2017-02-21 11:16
Closing as a duplicate of #5047, please take a look at the solution there, it might help.

**Closed by Banandrew** 2017-02-21 11:16 UTC
Labels: Duplicate
