### ISSUE TITLE
Misaligned attached div in the examples

### ISSUE THREAD

**Issue by zerkms** [Semantic-Org/Semantic-UI#4698] opened 2016-11-01 00:04 UTC
The most bottom example on the http://semantic-ui.com/examples/attached.html page has the top `div` misaligned to the table below.

Reproducible in chrome, edge, firefox.

![screenshot 2016-11-01 13 02 46](https://cloud.githubusercontent.com/assets/302295/19875678/a5ca8044-a033-11e6-836f-60cb8ecddd05.png)

**Comment by Banandrew** [comment] 2017-02-15 10:52
It seems that `.ui.attached.table` is responsible:
```CSS
.ui.attached.table {
  margin: 0em @attachedHorizontalOffset;
  /* Equals to -@borderWidth that equals to 1px, or “-1px” */
}
```

**Comment by Banandrew** [comment] 2017-02-24 03:46
Turned out it’s a duplicate of #4248.

**Closed by Banandrew** 2017-02-24 03:46 UTC
Labels: Duplicate
