### ISSUE TITLE
Gulp doesn't build semantic.min.css

### ISSUE THREAD

**Issue by tuanhuu** [Semantic-Org/Semantic-UI#6632] opened 2018-10-17 04:32 UTC
After run gulp build, just semantic.min.js built, dont see css. And cant import these file to create-react-app because it outside src folder

**Comment by ColinFrick** [comment] 2018-10-17 04:35
Duplicate of #6622

**Closed** 2018-10-17 07:06 UTC
Labels: Duplicate

**Comment by jlukic** [comment] 2018-10-21 21:07
`2.4.2` released with fix
