### ISSUE TITLE
Chinese mirror station became a pirated game website

### ISSUE THREAD

**Issue by ngauerh** [Semantic-Org/Semantic-UI#6799] opened 2019-04-29 06:49 UTC
I found that the Chinese mirror station [www.semantic-ui.cn](http://www.semantic-ui.cn) has become a pirated game website, This is not allowed by Chinese law. please handle it in time.
![捕获](https://user-images.githubusercontent.com/17571466/56879925-5de91480-6a8d-11e9-8f3a-9de72f4c3cbf.PNG)

**Comment by hammy2899** [comment] 2019-04-29 07:02
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/6759

**Closed by hammy2899** 2019-04-29 07:02 UTC
Labels: Duplicate
