### ISSUE TITLE
[Dropdown] overflow:auto or overflow:scroll breaks Dropdown

### ISSUE THREAD

**Issue by alexanderwe** [Semantic-Org/Semantic-UI#5441] opened 2017-06-06 15:55 UTC
When I am trying to assign a Dropdown to a vertical menu and the menu has the property `overflow:auto`, the Dropdown is not displayed at all.

Here is a small fiddle which shows the issue. Hope this will help to reproduce the error.
http://jsfiddle.net/phocLvu5/13/

Also if the fiddle may not work, here is a screenshot demonstrating the issue.

![bildschirmfoto 2017-06-06 um 17 43 00](https://user-images.githubusercontent.com/12934015/26838780-6d6b097c-4ae1-11e7-8f5a-98eb59d66f17.png)

Thanks in advance for looking at it.

**Comment by Banandrew** [comment] 2017-06-06 19:19
Hi @alexanderwe, I think it’s a duplicate of #1340.

**Closed by Banandrew** 2017-06-06 19:19 UTC
Labels: Duplicate
