### ISSUE TITLE
[Dropdown] module.is.onScreen returns wrong result when context is changed

### ISSUE THREAD

**Issue by cubicle** [Semantic-Org/Semantic-UI#5366] opened 2017-05-12 14:47 UTC
Have a look at this [fiddle](http://jsfiddle.net/44czvft4/2/). The menu opens above the dropdown and not below as expected.

The reason is that module.is.onScreen uses $currentMenu.offset() for it's calculations. Unfortunately the returned coordinates are relative to the document and not relative to the supplied context. 

I think you need to calculate the offset relative to the supplied context, like this:

```javascript
            calculations = {
              context: {
                scrollTop : $context.scrollTop(),
                offset    : $context.offset(),
                height    : $context.outerHeight()
              },
              menu : {
                offset: $currentMenu.offset(),
                height: $currentMenu.outerHeight()
              }
            };
            onScreen = {
              above : (calculations.context.scrollTop) <= calculations.menu.offset.top - calculations.context.offset.top - calculations.menu.height,
              below : (calculations.context.scrollTop + calculations.context.height) >= calculations.menu.offset.top - calculations.context.offset.top + calculations.menu.height
            };
```

**Comment by Banandrew** [comment] 2017-05-12 16:59
Hi @cubicle, thank you, but it seems to be a duplicate of #1340.

**Comment by cubicle** [comment] 2017-05-16 14:16
Hi @Banandrew, im not sure about this.  #1340 is marked as enhancement request and it's scope is not really clear to me. I'm not having a problem with the context's overflow property. Here is a [fiddle](http://jsfiddle.net/44czvft4/3/) without it.

The problem is the calculations doesn't respect the context's position at all.

**Comment by Banandrew** [comment] 2017-05-16 14:38
@cubicle I apologize, you’re right.

**Comment by jlukic** [comment] 2018-01-29 02:23
The `openLeftward` function had the same issue with not correctly calculating context offset.

Example here
http://jsfiddle.net/ogrdhaf0/

I've added your fix @dannybies and also fixed the leftward function

**Closed by jlukic** 2018-01-29 02:23 UTC
Labels: Confirmed Bug

**Comment by virulentt** [comment] 2018-02-06 14:26
I initialized my dropdown with the context being the highlighted container in the picture like this : 
`($(".actions.ui.dropdown") as SemanticUI).dropdown({ action: "hide", context: $("#container"), keepOnScreen: true });`

![image](https://user-images.githubusercontent.com/5427239/35864378-966fe762-0b1f-11e8-814f-96176e3ad96f.png)

It doesn't seem to calculate according to the size of my context. Blue is the allowed container, green is the padding and orange is the margin. (red squares are sentitive information).

I'm on 2.2.14.
