### ISSUE TITLE
Dropdown inside hidden element when initiated doesn't display properly

### ISSUE THREAD

**Issue by joshbodine21** [Semantic-Org/Semantic-UI#1888] opened 2015-02-28 00:09 UTC
It appears that if I have a dropdown that I have initiated inside of a hidden section of my form, that gets displayed when I select a corresponding checkbox, the resulting dropdown gets partially hidden under following elements. It looks like it is a problem with the z-index possibly. If it is not hidden upon the form loading it works fine.

**Comment by jlukic** [comment] 2015-02-28 00:54
Please create a test case there is a js fiddle you can form in the readme

**Comment by joshbodine21** [comment] 2015-03-07 01:02
Sorry for the delay: here is the test case of a mock up form: http://jsfiddle.net/gf96hf5n/

If the dropdown is hidden on page load, and then is displayed via a checkbox, the menu items get hidden underneath any content that follows. If the dropdown is visible on page load and not hidden, then there is no issue.

**Comment by pureux** [comment] 2015-05-23 04:33
I'm also experiencing the same issue.  I have the dropdowns initialized inside a collapsed accordion, inside a sidebar.  The selection dropdowns, when expanded, sit underneath (instead of over top) labels and checkboxes below the dropdown.

**Comment by pureux** [comment] 2015-05-23 04:37
@jlukic this appears to be a legitimate issue, and it is reproducible in the jsFiddle @joshbodine21 created.  I'm experiencing the same issue in my app, as described in my previous comment.  Would you please consider re-opening the issue and investigating?  Thanks.

**Comment by jlukic** [comment] 2015-05-23 06:50
Didn't notice test case in the closed issue. I'll check again.

**Comment by pureux** [comment] 2015-08-14 19:44
I upgraded to the newly released Semantic UI 2.0 and the issue is resolved in the latest version.  Thanks!

**Closed** 2015-08-14 20:44 UTC
Labels: Already Fixed, Evaluating Bug / Change
