### ISSUE TITLE
Labeled button

### ISSUE THREAD

**Issue by Berger92** [Semantic-Org/Semantic-UI#6507] opened 2018-07-25 19:33 UTC
Something went wrong with the labeled buttons: value is hidden by default, you need to hover over the value to be able to see it. I guees it happened with the latest release.

https://semantic-ui.com/elements/button.html#labeled

**Comment by ColinFrick** [comment] 2018-07-25 20:10
Duplicate of #6439

**Closed** 2018-07-25 20:57 UTC
