### ISSUE TITLE
Semantic-UI should run faster. jQuery is slow. prefer native JS

### ISSUE THREAD

**Issue by milahu** [Semantic-Org/Semantic-UI#6703] opened 2018-12-08 12:58 UTC
### Expected Result
run faster

### Actual Result
running slow : P

### Version
2.4.2

### Desc
this concerns the abuse of jQuery.

when i see code like ...
```
              module.debug('Creating entire dropdown from select');
              $module = $('<div />')
                .attr('class', $input.attr('class') )
                .addClass(className.selection)
                .addClass(className.dropdown)
                .html( templates.dropdown(selectValues) )
                .insertBefore($input)
              ;
```
in src/definitions/modules/dropdown.js line 360

... i suspect: this cant be fast.

and its not:

- native createElement is [faster by factor 4](https://jsperf.com/jquery-vs-createelement/5)
- native setAttribute is [faster by factor 4](https://jsperf.com/jquery-attr-vs-native-setattribute/28) (setProperty only works for standard attributes)
- native classList.add is [faster by factor 2](https://jsperf.com/jquery-addclass-vs-native-methods/13)
- native innerHTML is [faster by factor 1.5](http://jsben.ch/wd1Ie) (also faster than createDocumentFragment + createElement + appendChild)
- jQuery.html is [really slow](https://jsperf.com/xml-vs-html-parse-and-render-2) with 'complex xml input' (innerHTML should be fine, since most pages use XHTML, so strings are parsed as XHTML)

etc ...

templates.dropdown is fast, cos it only concats strings
in src/definitions/modules/dropdown.js line 3900

references

https://ilikekillnerds.com/2015/02/stop-writing-slow-javascript/

**Comment by ColinFrick** [comment] 2018-12-08 13:01
Duplicate of #1175

**Comment by milahu** [comment] 2018-12-08 13:11
sorry for dupe-ing

please consider linking to the work-in-progress [Vanilla-Semantic-UI](https://github.com/morganbarrett/Vanilla-Semantic-UI) in the readme

**Closed** 2018-12-08 13:42 UTC
Labels: Duplicate

**Comment by Atulin** [comment] 2018-12-08 20:05
Unfortunately, #1175 has been buried, and [Vanilla-Semantic-UI](https://github.com/morganbarrett/Vanilla-Semantic-UI) hasn't seen any updates in 7 months. Looks like native version is still a ways off.

Normally I'd suggest adding your findings about the speed to a relevant issue on [Fomantic-UI](https://github.com/fomantic/Fomantic-UI) repo, but fomantic/Fomantic-UI#20. Unless their stance has changed.

**Comment by hammy2899** [comment] 2018-12-08 21:00
@Atulin https://github.com/fomantic/Fomantic-UI/wiki/3.0-Road-Map

> Rewrite JS components in ES6

**Comment by Atulin** [comment] 2018-12-08 21:09
Under `Nice to have/want`.
Still, having it on the roadmap at all is a good thing. I think it could be a good idea to add a link to the roadmap to the referenced issue, since that's the first thing that pops up when searching for `jquery`.

**Comment by milahu** [comment] 2018-12-08 21:14
thanks for your feedback : ]

quoting [rishavs](https://github.com/fomantic/Fomantic-UI/issues/20#issue-331098269)

> ... removing jquery seems to be one of the most requested features in SUI ...

removing jQuery is rather a luxury problem, with only small gains.
these feature requests show, that SUI is mature, and only lacks like 5% in speed/RAM.

> Vanilla-Semantic-UI hasn't seen any updates in 7 months

luxury problem : /

what could help here, are [macros for JS](https://jlongster.com/Stop-Writing-JavaScript-Compilers--Make-Macros-Instead)

with macros, we could move the abstraction away from JS into the macro language
and use the macro processor, to 'compile' native JS

looks like i finally found a use case for lisp / scheme / rust / nix / sweetjs ...
