### ISSUE TITLE
[List] Indent broken on ordered lists from the level 3

### ISSUE THREAD

**Issue by J2BB** [Semantic-Org/Semantic-UI#5003] opened 2017-02-10 12:57 UTC
Hi,

It seems "list" styles are broken on ordered lists, from the level 3.
The indent is not adjusted in terms of the count level, and the text come over the counter.
I'm using Semantic-UI in version 2.2.7.

![image](https://cloud.githubusercontent.com/assets/5703714/22827469/54f0c5ca-ef98-11e6-8150-0a0398c0670c.png)

Help ! :)

**Comment by Banandrew** [comment] 2017-02-10 13:01
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by J2BB** [comment] 2017-02-10 13:13
Here is my test case : http://jsfiddle.net/afx20rkv/

Browser : Google Chrome Version 58.0.3006.0 canary (64-bit)
Semantic UI version : 2.2.7

**Comment by Banandrew** [comment] 2017-02-10 13:36
@J2BB Closing as a duplicate of #2639. Sorry for asking the test case, should’ve checked confirmed issues beforehand.

**Closed by Banandrew** 2017-02-10 13:36 UTC
Labels: Duplicate
