### ISSUE TITLE
High density flag assets

### ISSUE THREAD

**Issue by talha-asad** [Semantic-Org/Semantic-UI#4210] opened 2016-07-04 02:01 UTC
Flag assets file should be either an SVG or have a @2x version for retina displays.

**Comment by lfilho** [comment] 2016-09-21 19:42
This is probably a dupe of #1240 But I agree and +1'd it! :)

**Closed** 2017-03-10 13:15 UTC
Labels: Duplicate

**Comment by lubber-de** [comment] 2020-07-26 20:05
For version 2.9 of the active community fork Fomantic-UI, the sprite flags are going to be replaced by the same SVG icons as already available for the [emoji component](https://fomantic-ui.com/elements/emoji.html)
https://github.com/fomantic/Fomantic-UI/pull/1190
