### ISSUE TITLE
Change position close icon in modal when it has long modal

### ISSUE THREAD

**Issue by endlessdev** [Semantic-Org/Semantic-UI#4644] opened 2016-10-13 13:54 UTC
Hello Semantic UI users.
I'm semantic ui been used with a problem found.
That about close icon in long modal.

When transition is end of that has long modal class,
close icon is move out of control.

Here is my code

``` HTML
<div class="ui long modal filter-modal">
    <i class="close icon"></i> // that is move out of control when modal has long modal of transition.
    <div class="header">
        ...
    </div>
    <div class="content">
         ...
    </div>
</div>
```

Please check this problem.
Thank you.

P.S Sorry for my english is not good

**Comment by kmd1970** [comment] 2016-12-07 21:56
I second that, same issue with 2.2.6 and IE 11. Firefox seems ok.
Example:
[Imgur](http://i.imgur.com/dR56NyS.jpg)

**Comment by Banandrew** [comment] 2017-02-20 01:10
Hi, I’m not sure if it’s a duplicate of #4676, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by Banandrew** [comment] 2017-03-02 07:04
Closing it for now as a duplicate of #4676.

**Closed by Banandrew** 2017-03-02 07:04 UTC
Labels: Duplicate, Needs Test Case
