### ISSUE TITLE
[Menu] Search should not cut off input text

### ISSUE THREAD

**Issue by koddsson** [Semantic-Org/Semantic-UI#5281] opened 2017-04-17 12:28 UTC
Here's a fiddle demonstrating the issue. I noticed this first in the semantic docs when there's a search input in the menu component so I assume that it's pretty easy to reproduce. The fiddle is basically a copy of the code in the docs.

- Fiddle: https://jsfiddle.net/rrc7an6x/

Here's a screenshot of what I'm getting in case the issue is not re-producable:

![image](https://cloud.githubusercontent.com/assets/318208/25088853/31f38882-2369-11e7-87ad-3630fabd8204.png)

This seems to be because a `border-radius` on the input, since only the first letter has the cutoff:

![image](https://cloud.githubusercontent.com/assets/318208/25088872/64e9bf68-2369-11e7-96ac-fcacd884ca7f.png)

#### Info
- Browser: Google Chrome Version 57.0.2987.133 (64-bit)
- OS: MacOS Sierra 10.12.4

**Comment by Banandrew** [comment] 2017-04-17 14:21
Thanks. I wonder why it can’t be reproduced on [the menu component’s documentation page](https://semantic-ui.com/collections/menu.html#search), the markup seems to be identical; the clipping has always been there, just not that severe.

**Comment by koddsson** [comment] 2017-04-17 15:00
Hmm, I'm able to reproduce it in the menu documentations page:

![image](https://cloud.githubusercontent.com/assets/318208/25092766/a0db92e8-237e-11e7-953a-2c2283a1238f.png)

**Comment by jlukic** [comment] 2017-04-17 15:17
I'm seeing full descendors in the same example in Chrome 57. What browser are you checking with @koddsson

**Comment by jlukic** [comment] 2017-04-17 15:25
It does look like its cutoff by 1px on base em. Probably could be more/less noticable if base em was different as well.

**Comment by jlukic** [comment] 2017-07-02 20:20
Fixed in `2.1.11` thank you for your patience.

**Closed by jlukic** 2017-07-02 20:20 UTC
Labels: Confirmed Bug
