### ISSUE TITLE
Floating message does not float

### ISSUE THREAD

**Issue by nileshbits** [Semantic-Org/Semantic-UI#3429] opened 2015-12-03 10:33 UTC
The div "ui message floating" does not float above the underlying content. It takes up space as any normal content does.

I'm using chrome 46 on win 10.

**Comment by IonutBajescu** [comment] 2016-09-05 10:14
Hey @nileshbits,

Although most probably you've already fixed the issue yourself, is there any chance you could create a working jsfiddle so we can reproduce it as well?

**Comment by EnriqueVidal** [comment] 2017-09-18 03:40
Hey, if you guys are still interested [this](https://github.com/Semantic-Org/Semantic-UI/issues/5222#issuecomment-330124114) is how it worked for me.

**Comment by Banandrew** [comment] 2017-09-18 08:31
Hi @EnriqueVidal, and thanks for posting here; closing the issue as a duplicate of #5222.

**Closed by Banandrew** 2017-09-18 08:31 UTC
Labels: Duplicate
