### ISSUE TITLE
[Dropdown] Set exactly fires an empty string

### ISSUE THREAD

**Issue by jukestar** [Semantic-Org/Semantic-UI#4914] opened 2017-01-16 09:41 UTC
Using "set exactly" to set the value of a dropdown, fires off an empty string in onChange.

http://jsfiddle.net/91rp1v0L/2/

1. Watch the console output
2. Click "Set Value"

Expected:
I would expect that onChange only would occure once, when the actual value is set.

Actual:
onChange happens two times, first with an empty value, the second time with the actual value.

**Comment by dhvsandeep** [comment] 2017-01-19 11:35
Yeah, if there are multiple elements in that array, it'll fire multiple times, each time single element change ! I also don't know why it is firing first value as empty. 

Is there anyway complete array is selected at once instead of element by element ?
I'm also expecting a solution !

**Comment by philrykoff** [comment] 2017-03-02 09:39
As `set exactly` triggers onChange after each individual change as stated in #4913, it obviously also fires after initially clearing the dropdown of all existing values. If #4913 is considered a bug, this should be considered a duplicate of it. If it isn't, this should be closed.

**Comment by Banandrew** [comment] 2017-03-02 11:30
@philrykoff Thanks, you’re right, this one can probably be closed.

**Closed by Banandrew** 2017-03-02 11:30 UTC
Labels: Duplicate
