### ISSUE TITLE
the domain name "www.semantic-ui.cn" redirects to a game website

### ISSUE THREAD

**Issue by xinst** [Semantic-Org/Semantic-UI#6835] opened 2019-06-24 05:14 UTC
the Chinese mirror site is not available for now

www.semantic-ui.cn

**Comment by prudho** [comment] 2019-06-24 12:36
Yup, already issued in #6736.

**Comment by vinayakkulkarni** [comment] 2019-11-27 13:56
Duplicate of #6736

**Closed by vinayakkulkarni** 2019-11-27 13:56 UTC
Labels: Duplicate
