### ISSUE TITLE
.search.dropdown cannot move cursor

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2199] opened 2015-05-02 21:08 UTC
After I've selected an item from dropdown list, i cannot delete that item pressing 'delete' key and cannot navigate the text of the item using right\left keys.

**Comment by jlukic** [comment] 2015-05-03 16:42
I'm not sure what happened there, but it appears there's some regression with `1.x` keyboard shortcuts

**Comment by jlukic** [comment] 2015-05-04 16:46
Fixed in patch today.

**Closed by jlukic** 2015-05-04 16:46 UTC
Labels: Bug, High Priority

**Comment by avalanche1** [comment] 2015-05-05 10:14
Jack, the fix don't work.
Checked it on my meteor project and on SUI.com

**Comment by jlukic** [comment] 2015-05-05 21:01
Seems to be fine at semantic-ui.com at http://semantic-ui.com/modules/dropdown.html#search-selection

Clear cache?

**Comment by avalanche1** [comment] 2015-05-06 08:57
Cleared. Still serving 1.12.1 on sui.com. You sure everything's fine with sui.com link to master repo?

**Comment by avalanche1** [comment] 2015-05-06 09:04
But anyway, I have 1.12.2 in my meteor app and the fix doesnt seem to work. I'll make a fiddle once the versioning confusion is sorted.

**Comment by avalanche1** [comment] 2015-05-08 15:42
well, maybe this needs reopening.
still aint working.http://jsfiddle.net/pybxztu2/1/

**Comment by jlukic** [comment] 2015-05-08 16:40
Delete key and arrow keys seem to be fine in your fiddle?

**Comment by avalanche1** [comment] 2015-05-09 14:29
Is it a question or a statement?
In the fiddle the keys ```delete, left, right``` aint working after I've selected an item from dropdown list.

**Comment by jlukic** [comment] 2015-05-09 15:37
The bug I fixed was left/right arrows not working during selection. 

This is expected behavior. After making a selection it adjusts the underlayed text content. This could contain other non string values like images or labels and is unselectable. It is not part of the current input.
http://beta.semantic-ui.com/modules/dropdown.html#search-selection
