### ISSUE TITLE
[Sidebar] Closeable property of Sidebars being ignored

### ISSUE THREAD

**Issue by mojimi** [Semantic-Org/Semantic-UI#5364] opened 2017-05-11 19:33 UTC
I made a fiddle that exemplifies the issue : https://jsfiddle.net/p3oswhje/5/

Even when 'closeable' is set to false, when you click outside the sidebar, it closes.

**Comment by Banandrew** [comment] 2017-05-12 07:28
Hi @mojimi, it seems to be a duplicate of #5329.

**Closed by Banandrew** 2017-05-12 07:28 UTC
Labels: Duplicate
