### ISSUE TITLE
LESS npm package missing 'themes/*/assets'

### ISSUE THREAD

**Issue by Panoplos** [Semantic-Org/Semantic-UI#5821] opened 2017-10-01 05:00 UTC
Linking here due to inactivity on the less git.

https://github.com/Semantic-Org/Semantic-UI-LESS/issues/28

**Comment by Banandrew** [comment] 2017-10-07 10:47
Hi @Panoplos, sorry for the delay, but I can’t seem to reproduce, and all assets are there. Did you manage to get it fixed during the week?

**Comment by Panoplos** [comment] 2017-10-09 09:11
No, just tested again, and still no-go. Did a `yarn remove semantic-ui-less` and `yarn add semantic-ui-less`.

```shell
~/Documents/Development/Node.js/project
⟩ find node_modules/semantic-ui-less/ -name assets

~/Documents/Development/Node.js/project
⟩ 
```

**Comment by Banandrew** [comment] 2017-10-09 11:18
@Panoplos No.

**Comment by Panoplos** [comment] 2017-10-10 04:20
OK, can you try in a clean environment or give me some pointer as to how to get this fixed?

**Comment by Banandrew** [comment] 2017-10-10 09:31
@Panoplos I would if I could, but I don’t know why it happens—I tried several things yesterday, but nothing was reproducing the issue. I’m sorry that it happened, the only I can do is to summon the maintainer, perhaps he’ll have time to take a look at it this week; @jlukic.

**Comment by Panoplos** [comment] 2017-10-11 03:08
Yeah, it is a strange issue, indeed, but it is a showstopper for us. If I can provide any further info that would help, just ask.

**Comment by 1-14x0r** [comment] 2017-10-11 04:20
@Panoplos I just tested this can i can not reproduce either. However I made you a quick fix.

here is a forked tag of the 2.2.13 release:
src => https://github.com/1-14x0r/Semantic-UI-LESS/tree/just-themes 
tag => https://github.com/1-14x0r/Semantic-UI-LESS/releases/tag/2.2.13a

basically remove the module from your package.json and extract the themes dir to overwrite your existin' one in the module.. 

Alternative You could also keep the module as it is, and copy over the static files you in your `src`. just make sure your build task copies over the assets. main.

i know its some hackery but that is the best idea i have. Sounds alot like some type of issue with your local configuration or network. o_0 

GLHF;

**Comment by Panoplos** [comment] 2017-11-08 04:58
I finally figured out what the problem was! In the default `.yarnclean` config file, it is specifying `assets` as a directory to "clean", which was deleting all assets. Really stupid problem and not sure why yarn clean has implemented defaults in this manner... I will report the issue in their repo.

**Comment by Panoplos** [comment] 2017-11-08 05:06
See: https://github.com/yarnpkg/yarn/issues/4879

**Comment by Banandrew** [comment] 2017-11-08 15:23
Thank you, @Panoplos. Their response seems to be reasonable, and I think the thread can now be closed as resolved.

**Closed by Banandrew** 2017-11-08 15:23 UTC
Labels: Cannot Reproduce, Evaluating Bug / Change
