### ISSUE TITLE
Add Horizontal/Vertical Slider

### ISSUE THREAD

**Issue by xerox95** [Semantic-Org/Semantic-UI#3974] opened 2016-04-28 18:17 UTC
Is it possible to add a Horizontal/Vertical Slider, like 
```html
<input id="slider1" type="range" min="100" max="500" step="10" />
```

this ?

**Comment by IonutBajescu** [comment] 2016-04-29 10:15
Duplicate of #1336.

**Closed** 2016-05-01 07:10 UTC
