### ISSUE TITLE
[SUGGESTION] Hide on certain screen sizes

### ISSUE THREAD

**Issue by Jncocontrol** [Semantic-Org/Semantic-UI#6697] opened 2018-12-01 19:21 UTC
I've been tampering with other frameworks (specifically materialize css) and they have a REALLY good feature where you can hide certain item on certain screen sizes, and as I thought about it Semantic doesn't have that (as far as I'm aware) and it would make our lives a little better as we develop for mobile users instead of making media queries which are a pain to implement.

It would be greatly appreciated to have this feature.

**Comment by lubber-de** [comment] 2018-12-01 22:11
I am using the css additions from https://github.com/Semantic-Org/Semantic-UI/issues/1114#issuecomment-201057438  which adds global support for

mobile only
mobile hidden,
tablet only
tablet hidden
computer only
computer hidden
large screen only
large screen hidden
widescreen only
widescreen hidden
or lower hidden

and works flawlessly so far

**Comment by hammy2899** [comment] 2018-12-02 19:30
Duplicate of https://github.com/Semantic-Org/Semantic-UI/issues/1114

**Closed by hammy2899** 2018-12-02 19:30 UTC
Labels: Duplicate
