### ISSUE TITLE
[label] basic label background-color typo?

### ISSUE THREAD

**Issue by ScorpioX** [Semantic-Org/Semantic-UI#6478] opened 2018-07-12 10:21 UTC
✔ BUGS

### Steps
Just check your official site
https://semantic-ui.com/elements/label.html#basic
https://semantic-ui.com/elements/button.html#labeled

### Expected Result
Colored basic label should display white background

### Actual Result
Background color appears the same as text, rendering text unreadable unless mouse hover

### Version
2.3.3

![screen shot 2018-07-12 at 6 18 24 pm](https://user-images.githubusercontent.com/14276/42627571-ffe09466-85ff-11e8-969c-b02c893690c0.png)
![screen shot 2018-07-12 at 6 19 18 pm](https://user-images.githubusercontent.com/14276/42627625-20ca1986-8600-11e8-97a8-a986ce4c9478.png)

The root cause seems a typo in label styling:
ui.basic.red.label {
    background-color: none #fff!important; // Deletes "none" makes the bug go away
    color: #db2828!important;
    border-color: #db2828!important;
}

**Comment by ColinFrick** [comment] 2018-07-12 12:21
Duplicate of #6439

**Closed** 2018-07-13 07:22 UTC
