### ISSUE TITLE
Sidebar creates pushable class which stays and changes background color + prevents page dimmer from working

### ISSUE THREAD

**Issue by Eliasvdb** [Semantic-Org/Semantic-UI#2087] opened 2015-04-08 21:01 UTC
Hello

I am trying to get the sidebar to work on a website. I have a page dimmer on my page which I use to display a login dialog. I also have a sidebar. Both work, but the sidebar does break my page dimmer when it gets opened.

The main cause for this is because the opening of the sidebar adds a pushable class to the body, and this class doesn't get deleted, it stays on the body. This causes two things:
* The background behind my body, the margin regions (body is at 70% width margin 0 auto), get a black color.
* When my page dimmer gets called, no interaction is possible because there seems to be a layer above it.

I don't know if I'm doind something wrong or if this is some kind of bug, but the removal of the pushable class seems to solve the problems. Do I need to do anything to remove the pushable class? I could remove it myself using jQuery but when I try that the slide out animation doesn't work (obviously).

I really hope anyone can shed some light on this, thanks!

How it should look:
![schermafbeelding 2015-04-08 om 16 58 00](https://cloud.githubusercontent.com/assets/9058581/7055308/8ae94800-de10-11e4-8052-9b7374af6717.png)

The black color after using the sidebar:
![schermafbeelding 2015-04-08 om 16 57 45](https://cloud.githubusercontent.com/assets/9058581/7055306/8ae4f138-de10-11e4-8f56-5cecea1afa9b.png)

The page dimmer which is broken after the use of the sidebar:
![schermafbeelding 2015-04-08 om 16 58 22](https://cloud.githubusercontent.com/assets/9058581/7055307/8ae8e13a-de10-11e4-95fe-54fbe47b687b.png)

**Comment by jlukic** [comment] 2015-04-09 21:48
I'm not sure the issue, the ui docs use both modals and sidebars together.

If you can create a test JSFiddle i can help debug, check readme for links to fork.

**Comment by Eliasvdb** [comment] 2015-04-10 13:29
Okay I created a little JSFiddle as you asked to illustrate the problem:

https://jsfiddle.net/bsw2dn3o/

When you click the fixed teal menu icon on the left, you'll see the sidebar slide in, but you'll also see that the sides of the website get a black color which doesn't go away. I already discovered that is because of the pushable class that is being added (to the body), but is there a fix for this behavior?

The dimmer seems to work in the fiddle, but the problem of the black color remains. Please let me know if there is a fix for this, or if I am doing something wrong.

Thanks.

**Comment by jlukic** [comment] 2015-04-10 14:13
http://jsfiddle.net/dzm8b28s/

**Comment by Eliasvdb** [comment] 2015-04-10 14:16
Okay, I see. But I need those margins, it is often done in web design or am I mistaken?

How would I be able to recreate the 70% body width and not get the blackness?

**Comment by miniskulljob** [comment] 2015-04-11 11:15
Well, you could put all the content inside a `div` and set its width to 70%, like I did [in this fiddle](http://jsfiddle.net/miniskulljob/pfL0g7q9/).

**Comment by Eliasvdb** [comment] 2015-04-13 15:30
Thanks @miniskulljob, that is working and seems like a good solution.

If you try to call the page dimmer though in your fiddle you'll see that there's a black layer before it and you won't be able to interact with it, but a simple z-index fixed that for me ;)

Seems like all is well now, thanks all.

**Comment by jlukic** [comment] 2015-04-13 15:33
Glad this worked. Closing discussion since there is no active bug

**Closed by jlukic** 2015-04-13 15:33 UTC
Labels: Discussion, Question

**Comment by v3rron** [comment] 2015-09-04 19:50
This issue is happening again on iOS safari and iOS simulator. I'm trying to use the sidebar as a bottom options menu, which then triggers modal confirm page. The UI breaks completely leaving me with black screen and the entire page is broken. It looks like there's a bunch of classes and elements left after triggering sidebar and modal which somehow conflict with each other.
Here's the example I'm using:
http://jsfiddle.net/wkztxqpq/1/

**Comment by LarsBuur** [comment] 2016-07-11 06:28
Continuing on the iOS sidebar. 

Using the example above from @Eliasvdb the output from the fiddle is this url: 
http://fiddle.jshell.net/dzm8b28s/show/

The problem is that if you try to display that specific page in either iOS simulator or in safari on iOS then the height of the sidebar is only the height of the content - and the rest is hidden. Please see this image as an illustration.
![screen shot 2016-07-11 at 08 26 31](https://cloud.githubusercontent.com/assets/3585707/16721656/43cb60b6-4741-11e6-8608-79255af4bd6d.png)
I have tried to add this css (from the sidebar docs).

'''
html.ios {
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}
html.ios,
html.ios body {
  height: initial !important;
}
'''
it is not clear from the docs (to me) if I manually should add the userAgent detection any ideas how this could be resolved?
