### ISSUE TITLE
[Dropdown] Selected multiple options are hidden (2.2.14)

### ISSUE THREAD

**Issue by Thanty** [Semantic-Org/Semantic-UI#6123] opened 2018-01-29 14:55 UTC
I've used to generate dropdowns from HTML in my forms, but Semantic 2.2.14 has a critical bug: selected options are hidden (but they are still considered as selected if you submit a form):

https://jsfiddle.net/3LaahL7e/1/

**Comment by harrisnl** [comment] 2018-01-30 09:56
I just noticed this same bug, no new debug info, just what @Thanty said.

**Comment by prudho** [comment] 2018-01-30 10:33
Seem to be introduced by 0fa58217adef109e22faa3722d2d4f30bef71ac5.

**Comment by iROCKBUNNY** [comment] 2018-02-01 12:29
I am suffering from this issue. This bug seems critical and needs a hot fix.

**Comment by adas172002** [comment] 2018-02-01 18:45
+1

**Comment by jbwl** [comment] 2018-02-02 09:24
I think I have the same symptom after upgrading to 2.2.14: Selected options (stored in the input tag's value attribute) are not displayed as preselected in the input field anymore. The input field appears empty.

**Comment by jamesdb** [comment] 2018-02-05 09:54
+1

**Comment by StevenKjp** [comment] 2018-02-08 08:42
+1

**Comment by camueller** [comment] 2018-02-11 11:49
I noticed this problem as well. After downgrading to 2.2.12 pre-selected options are displayed properly!

**Comment by jbwl** [comment] 2018-02-16 09:42
18 days without any reaction...this project seems pretty dead.

**Comment by kjo6152** [comment] 2018-02-19 08:37
I create pull request for this issue. #6169

**Comment by Thanty** [comment] 2018-02-20 08:07
Semantic-Org, thanks for the new 2.3.0 release! There are really good enhancements and features, **but**  we still cannot upgrade because of this one... Have to use 2.2.13.

**Comment by iROCKBUNNY** [comment] 2018-02-20 10:56
Are there any other possible work-arounds or tricks? What about some tweaks on the dropdown JS components when initializing them?

**Comment by iROCKBUNNY** [comment] 2018-02-20 13:03
@hammy2899 can help label this bug? This looks quite critical. Thanks a lot!

**Comment by thejhnz** [comment] 2018-02-27 04:15
+1

**Comment by jlukic** [comment] 2018-02-28 22:17
Will address in next patch.

**Comment by iROCKBUNNY** [comment] 2018-02-28 22:27
@jlukic Excited!

**Comment by bianjp** [comment] 2018-03-06 06:34
Just met the same problem, and found that it was caused by the change from `if(module.has.label(value))` to `if(module.has.value(value))` introduced in [0fa5821](https://github.com/Semantic-Org/Semantic-UI/commit/0fa58217adef109e22faa3722d2d4f30bef71ac5#diff-dbb1b936fdad1f63b3a01f86d9a54fd1R2589). Reverting this line is enough to fix it. But I'm not sure why it's introduced and whether reverting is appropriate or not.

Anyway, I hope that 2.3.1 can come soon.

**Comment by arturamaj** [comment] 2018-03-08 20:37
+1

**Comment by jlukic** [comment] 2018-03-14 00:05
I'll have time to address this issue, this sunday.

**Comment by jlukic** [comment] 2018-03-18 21:19
This should be fixed in `0e5c824`, with a tiny change.

Labels were checking if the dropdown value already was set (for dupe matching) but because of the order of operations with initializing multi selects from `<select>` this would always prevent labels from being drawn.

**Comment by jlukic** [comment] 2018-03-19 00:49
This is fixed in `2.3.1` releasing tonight

**Closed by jlukic** 2018-03-19 00:49 UTC
Labels: Confirmed Bug, High Priority

**Comment by subramn** [comment] 2018-09-01 19:35
I am also running into this problem, my pre-selected options are not showing. any workaround available

**Comment by jbwl** [comment] 2018-09-04 15:39
subramn - it has been fixed in 2.3.1

https://github.com/Semantic-Org/Semantic-UI/issues/6123#issuecomment-374072333
