### ISSUE TITLE
[Search] `url` seems not work

### ISSUE THREAD

**Issue by zisten** [Semantic-Org/Semantic-UI#3111] opened 2015-09-29 11:07 UTC
The `fields`'s `url` field is not work at this document page [Search - Examples](http://semantic-ui.com/modules/search.html#using-different-response-fields). Not work in my case with version both 2.1.3 and 2.1.4. In previous 2.0.x, it works as expected.

Is it a document error or deprecated or a bug?

Thank you for reply.

**Comment by jlukic** [comment] 2015-09-29 15:03
It's working for me on settings pages. Keep in mind its `apiSettings: { url: 'foo' }`

**Comment by zisten** [comment] 2015-09-30 01:07
@jlukic , not the `apiSettings` `url`, it is the `fields` `url` field - actually it does not point to anything.

**Comment by unplugandplay** [comment] 2015-10-05 13:11
just fixed it on my machine : 
            $.each(category.results, function(index, result) {
              if(response[fields.url]) {
                html  += '<a class="result" href="' + response[fields.url] + '">';
              }
              else {
                html  += '<a class="result">';
              }

The problem is : 
   if(response[fields.url]) {
                html  += '<a class="result" href="' + response[fields.url] + '">';
              }
use "response" instead of "result" 
And  fields: { ... } should define  url : 'url'
here only actionURL       : 'url'  is defined

**Comment by xaeroseven** [comment] 2015-10-05 17:15
We are experiencing this same issue as well, thanks for the patch notes @unplugandplay.  @jlukic - let us know if there is a patch release upcoming to resolve this, thanks!

**Comment by hluckenb** [comment] 2015-10-15 00:31
Thanks @unplugandplay, thought I was crazy. Fixed for me as well.

**Comment by Banandrew** [comment] 2015-10-23 20:31
Not only that, it seems you can't follow a href with Enter key—it just pastes the title into the search field. If someone knows how to fix it until a future release, please reply.

**Comment by jlukic** [comment] 2015-10-23 23:18
I'll try to get to this shortly

**Comment by jlukic** [comment] 2015-11-01 18:59
Fixed with #3227

**Closed** 2015-11-01 19:00 UTC
Labels: Confirmed Bug
