### ISSUE TITLE
[Docs] Fixed Menu Issue in Mobile Chrome

### ISSUE THREAD

**Issue by Basgrani** [Semantic-Org/Semantic-UI#1644] opened 2015-01-16 10:10 UTC
You can play go this url from a mobile device and by scrolling up and down:

http://semantic-ui.com/elements/button.html

![menu fixed error](https://cloud.githubusercontent.com/assets/3121125/5774604/d726ff64-9d6f-11e4-8f40-c5e83bd2042c.PNG)

I've tried it on an iPhone 6 / ios 8.1.2 / in Chrome and Safari

If we cancel semantic.js works well, so I suspect it may be a bug.

Thanks in advance, are doing a great job!

**Comment by jlukic** [comment] 2015-01-16 16:18
I'm checking on my iPhone 5S and everything appears fine regardless of how much i scroll up or down.

Can anyone else confirm they are seeing this on their device?

**Comment by Basgrani** [comment] 2015-01-16 18:14
Attached video so they can see better:

https://www.dropbox.com/s/tufvd51dt5qqdpv/nav-fixed-error-iphone6-plus.mov?dl=0

**Comment by jlukic** [comment] 2015-01-16 19:36
I am seeing the error in chrome for iOS, but not native safari browser.

Odd its just `position: fixed` no extra JS. 
http://jsfiddle.net/8m62jkjk/show/

I'm seeing that even a simple jsfiddle that doesn't use semantic seems not to stick in chrome iOS when inside a jsfiddle iframe.
http://jsfiddle.net/1btcsoxf/

**Comment by Basgrani** [comment] 2015-01-17 19:26
Hi, I managed to find what triggers the error:

1 - Here I show the error in a video and a url you can try:

https://www.dropbox.com/s/a22nawrnbfrnuqs/menu-fix-not-work.mov?dl=0

http://labs-app.com/semantic-ui/menu-fix-with-bug/

2 - Here a video working well and a url you can try:

https://www.dropbox.com/s/qhvbyr9df2w9t1w/menu-fix-work.mov?dl=0

http://labs-app.com/semantic-ui/menu-fix-without-bug/

- The error occurs when this line is active:

$('.sidebar.menu').sidebar('attach events', '.toggle-sidebar');

- If disabled works well:

//$('.sidebar.menu').sidebar('attach events', '.toggle-sidebar');

Thanks in advance

**Comment by Basgrani** [comment] 2015-01-21 19:47
Hi, has reproduced the error?

**Comment by Basgrani** [comment] 2015-01-25 16:46
have been able to reproduce the error?

Thanks

**Comment by jlukic** [comment] 2015-01-26 01:31
I have in Chrome on IOS. I am unsure of how to move forward however since it doesnt appear to be from any error in the docs code. Everything fine on IOS Safari, and Chrome Win/Mac

**Comment by Basgrani** [comment] 2015-01-26 13:10
you have the chance to try on a iphone 6 plus, ios 8.1.2 / in Chrome 40.0.2214.69?

if it's any more help I found a way to provoke the most direct mistake, and when we activate this:

$('.toggle-sidebar').click(function () {
        $('.sidebar.menu').sidebar('toggle');
});

No error until I clik on '.toggle-sidebar'.

That figure is similar to what mentioned above, but this is caused immediately:

$('.sidebar.menu').sidebar('attach events', '.toggle-sidebar');

I think the error might be in the setting that makes the js code when events are triggered sidebar. The elements css fixed? with a transition to positioning position directly instead?. Maybe when you scroll to touch the repositioning of the item is delayed, no?

Thanks

**Comment by kvetoslavnovak** [comment] 2015-02-01 05:37
I confirm the example links with mistake and fix. I am using iPam/iOs and Safari.

**Comment by jlukic** [comment] 2015-02-01 17:06
What version of iOS?

**Comment by kvetoslavnovak** [comment] 2015-02-01 21:45
IOS 8.1.3. IPad 2

**Comment by Basgrani** [comment] 2015-05-06 14:21
something new? this point is important, I think.

It occurs in his official web semantic, so any errors are discarded implementation on our part.

still occurs in versión 1.12.1

Thanks

![error_sidebar](https://cloud.githubusercontent.com/assets/3121125/7495078/e8b6b0a6-f40b-11e4-9f92-ef9f20e1f5f2.PNG)

**Comment by kvetoslavnovak** [comment] 2015-05-09 18:05
The issue with iPad/iPhone Safari is aslo still the same. It is even worse in beta Semantic 2.0. 
Moreove to have such an issue in Semantic landing page could make not so great impression, which is a shame.

**Comment by jlukic** [comment] 2015-06-08 15:37
@kvetoslavnovak @Basgrani After many months of having no clue about the cause of this. I've added a fix.  https://github.com/Semantic-Org/Semantic-UI/commit/fe7e04e6ac7fa7962651d7a6a330c3fbe3be138d

The fix that was used to solve iOS autoresizing for offscreen content, which caused overflow to not be on document #1985 prevents Chrome's mobile optimizations for fixed content on scroll position. This will be fixed in `2.0` and on next beta deploy.

**Closed** 2015-06-08 15:38 UTC
Labels: Docs Issue

**Comment by kvetoslavnovak** [comment] 2015-06-09 19:45
Great! Thank you. I can confirm now it works like a charm :-)
